hmcts/vh-admin-web

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.css
AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.html

https://tools.hmcts.net/jira/browse/VIH-4460
Adjusted the style for headers and date in questionnaire list view:
Before:
After:
[ ] Yes
[X] No

Fixed css for list view

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts

n/s
Changed one of the service methods from `Observable` to `Promise` as a first step and added in caching of the value. In doing so I found that all the tests were injecting a service and simplified it. Many of the tests were also testing the mocked sessions storage and actually had incorrect test cases as a result so I fixed that too.
```
[ ] Yes
[X] No
```

Cleaned up tests

---

AdminWebsite/AdminWebsite/ClientApp/angular.json
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts

n/a
Babysteps but improvements.
I've moved this one block of code from `ngInit` to `ngAfterViewInit` because the `ViewChild` actually only gets populated in that step. I've no idea how this actually worked up until now.
See:[angular viewchild](https://blog.angular-university.io/angular-viewchild/) and [lifecycle hooks](https://angular.io/guide/lifecycle-hooks)
Also removed the use of `self`, it's javascript thing and we shouldn't need to use it if we keep our scopes straight.
```
[ ] Yes
[X] No
```

Moved code to use correct lifecycle order

---

AdminWebsite/AdminWebsite.AcceptanceTests/Pages/AddParticipants.cs
AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantsSteps.cs

n/a
I've found on a failure of acceptance test that it's very hard to read out what's actually going wrong. This is because the fluent assertion doesn't play nicely with methods so I've switched over to properties instead.
Compare this error output from before:
To this output afterwards:
```
[ ] Yes
[X] No
```

Changed selenium accessors from methods to properties for better reporting

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts

n/a
A first step of removing coded parent->child component dependency in code. Removing this and doing the binding in html instead will allow us to break apart the functionality, reducing complexity making it more testable and reducing risk for defects.
The plan is to remove the `this.searchEmail` calls entirely.
The most important thing here is trying to reduce the amount of `setTimeout` which creates temporal dependencies (for example calling a method, expecting something to be set afterwards and it's actually not until a few milliseconds have passed).
```
[ ] Yes
[X] No
```

Refactor component references

---

AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/SeleniumEnvironment.cs

n/a
Right now each deployment of a release overwrites the previous run in saucelabs. This means that it is very hard to track down the results of a de-deployment as it will be logged together with the previous release instead of the new one.  For example:
actually contains the result of this deployment:
Which of course is pretty hard to track down. So I simply added in the release number to the build name as well which should suffix the saucelab log entry with a `-x` for each build. Like this:
```
[ ] Yes
[X] No
```

Added release number to saucelabs build name

---

AdminWebsite/AdminWebsite.AcceptanceTests/Pages/MicrosoftLoginPage.cs

n/a
Yesterday 4/7, the option to choose to "stay signed in" when logging in on the microsoft portal was removed. This breaks all tests since they expect this button to appear.
This PR removes it.
See related:
https://github.com/hmcts/vh-video-web/pull/84
```
[ ] Yes
[X] No
```

Removed pressing the do not stay signed in button

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.html

https://tools.hmcts.net/jira/browse/VIH-4967
https://tools.hmcts.net/jira/browse/VIH-5008
Removed extra space before comma in participant details
Don't show pop up warning if changes are saved after edit heading details.
```
[ ] Yes
[X ] No
```

Fix pop up warning after edit and save, extra space before comma

---

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/DashboardSteps.cs
AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingDetailsSteps.cs

Fix for UserAccount casting error in 1.0.1+48 release
```
[ ] Yes
[X ] No
```

Fix for UserAccount casting error in 1.0.1+48 release

---

AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.spec.ts

VIH-7144
This test was failing due to the :focus selector returning undefined. Using document.activeElement instead.
```
[ ] Yes
[x] No
```

VIH-7144 use activeElement instead of :focus

---

AdminWebsite/AdminWebsite.UnitTests/ReferenceDataControllerTests.cs
AdminWebsite/AdminWebsite/Controllers/ReferenceDataController.cs

https://tools.hmcts.net/jira/browse/VIH-7113
Removing the HearingRole sort in the ReferenceDataController as it is now performed in the Bookings API.
```
[ ] Yes
[ X] No
```

VIH-7113 List party dropdown in alphabetical order

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-participant-list/booking-participant-list.component.ts

https://tools.hmcts.net/jira/browse/VIH-7474
The participant list in New Booking and Bookings List was adding observers with interpreters to the interpreter array as well as the observer array. Added a check to make sure the observer was not an interpretee and did not exist in the interpreter\interpretee list
```
[ ] Yes
[ X] No
```

VIH-7474 Person displayed twice in participant list

---

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj
AdminWebsite/AdminWebsite.AcceptanceTests/Configuration/AdminWebConfig.cs
AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs
AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs
AdminWebsite/AdminWebsite.AcceptanceTests/appsettings.json
AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
azure-pipelines.beta.yml
azure-pipelines.nightly.yml
azure-pipelines.release.yml
azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-7529
- Allow tests to run with eJud Test Users
- Added a config setting to turn this on and off if eJud is unavailable - DEFAULTED TO OFF UNTIL ITS READY IN ADMIN WEB
```
[ ] Yes
[X] No
```

VIH-7529 Use Ejud Users for tests

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/item/participant-item.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.ts

https://tools.hmcts.net/jira/browse/VIH-7410
- Extracted the handling of the participant selected event in add-participant.component to a method.
- Changed the logic in the second timeout within ngAfterViewInit to use the participant selected event handler as the logic was duplicated.
- Fixed the edit details not populating the first time edit is clicked.
- Fixed the interpretee list not populating when editing an interpreter 
```
[ ] Yes
[x] No
```

VIH-7410 edit interpreter journey issues

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonsControllerTest.cs
AdminWebsite/AdminWebsite/Controllers/PersonsController.cs

https://tools.hmcts.net/jira/browse/VIH-7932
- Added temporary filtering in PostPersonBySearchTerm to hide hearings reform judge accounts and ejud accounts.
```
[ ] Yes
[x] No
```

VIH-7932 Judge accounts available for selection for individual participants

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-participant-list/booking-participant-list.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-participant-list/booking-participant-list.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-details.service.ts

https://tools.hmcts.net/jira/browse/VIH-8784
Have added new sorting logic to the 'participant-list' and 'booking-participant-list' components. Added an additional property to the participant-detail model, linkedParticipants (which was already being sent over in the payload thats mapped into it.). This is to allow us to insert the interpreter below the their interpretee, via the link participant id.  Have had to update a few unit tests that use this model so they compile properly, thus the change looks abit bigger than it actually is.
```
[ ] Yes
[ X] No
```

VIH-8784 Refactor ordering of participants in admin web

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant-base/add-participant-base.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts

https://tools.hmcts.net/jira/browse/VIH-8812
Moved notObserver logic up to base class and now utilising this same logic for populating hearing role list, so that an interpreter can not be added if an observer/appraiser exists only. Also added supporting unit test.
```
[ ] Yes
[ x] No
```

VIH-8812 Fix for interpreter incorrectly showing in hearing role selection when valid interpretee (not appraiser/observer) exists already

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs
AdminWebsite/AdminWebsite/Controllers/HearingsController.cs

https://tools.hmcts.net/jira/browse/VIH-8792
Fixes an issue where the request to book a long hearing (25 days+) times out when the book + confirm feature is enabled.
The issue is addressed by doing the confirmations in parallel rather than sequentially.
The confirmations are performed in batches to limit the number of threads created at once.
```
[ ] Yes
[x] No
```

VIH-8792 Booking timeout exception for large multi day booking ranges

---

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list-routing.module.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.ts

https://tools.hmcts.net/jira/browse/VIH-8923
Fixes an issue where clicking the Back button on the booking details page sometimes takes you back to the dashboard instead of the booking list.
The main culprit is the url used by the returnUrlService. If this isn't set by the calling code, then it defaults to '~/' (the dashboard).
Also fixes the following:
- Start and end dates not persisting after clicking the Back button
- Search form open/close state not persisting after clicking the Back button
```
[ ] Yes
[x] No
```

VIH-8923 Booking details back button sometimes taking you to the wrong page

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts

https://tools.hmcts.net/jira/browse/VIH-9186
As part of the bug fix we are reinstating the fuzzy map search for participants (searching them using Contains instead of StartsWith), however this reintroduces a bug seen previously (VIH-8952) where a participant cannot be added to a booking if they have a similar email address to another existing user in the search results.
To get round this, we allow the email address to be validated if the email doesn't exist in the search results. If the email is valid then the Add Participant button will then be available once the rest of the form has been populated.
```
[ ] Yes
[x] No
```

VIH-9186 Allow participant with similar email to another user to be added

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts

https://tools.hmcts.net/jira/browse/VIH-9186
Fixes an issue introduced by the previous commit, where an "invalid email" warning is shown after selecting an existing email address when creating a booking.
We only want to trigger this.validateEmail() when creating a new user. We include an additional AND condition for emailIsValid to prevent it from triggering prematurely when searching for users.
```
[ ] Yes
[x] No
```

VIH-9186 Fix issue with invalid email warning being shown after selecting an existing email

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts

https://tools.hmcts.net/jira/browse/VIH-9227
Fixes a UI error upon updating a booking.
The booking confirmation page that they are redirected to looks for a value in session storage - this was not being populated upon updating a booking.
```
[ ] Yes
[x] No
```

VIH-9227 Users get "signed out" error whenever they edit a hearing

---

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts

https://tools.hmcts.net/jira/browse/VIH-9283
Fixes an issue where searching for a booking and clicking on it can throw an error due to it trying to look up a booking using an array index from a previous search.
Each time a search is performed, the row is deselected, so clear any selected indexes left over from the previous search.
```
[ ] Yes
[x] No
```

VIH-9283 Admin Web/Booking List page - Signed out error

---

AdminWebsite/AdminWebsite/ClientApp/src/app/services/edit-work-hours.service.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-search/vho-search.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-search/vho-search.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts

https://tools.hmcts.net/jira/browse/VIH-9355
Issues fixed:
- After adding a new non-availability, then going to add a second one, the last 2 rows are highlighted for validation errors
- Can't delete a non-availability after adding it
- Clicking Cancel keeps the new non-availability in the table, even though it hasn't been added yet. Fix by switching to edit mode before we push the new row to nonWorkHours array
The fix for the first 2 issues is to reload the non availabilities from the database after creating a new one so that we can populate the id for the new record.
```
[ ] Yes
[x] No
```

VIH-9355 Fix issues creating non-availabilities

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.ts

https://tools.hmcts.net/jira/browse/VIH-9489
Adds missing frontend validation for requiring both start and end time to be either populated or empty when editing work hours.
Includes some refactoring so that the form can support multiple validation errors
```
[ ] Yes
[x] No
```

VIH-9489 Editing work hours - require both start and end time to be populated or empty

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.ts
charts/vh-admin-web/Chart.yaml

https://tools.hmcts.net/jira/browse/VIH-9488
Fixes an issue where the confirmation message for saving work hours is still visible after clicking Edit or Cancel again.
```
[ ] Yes
[x] No
```

VIH-9488 Hide save work hours confirmation message when clicking edit or cancel

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.html

https://tools.hmcts.net/jira/browse/VIH-9497
Fixes an issue where attempting to re-upload (non) working hours after a failed upload does not work.
The issue is that the file is only processed when the uploaded file path changes, so if you try to re-upload the same file it won't work. Fix by clearing the selected file each time you click the Choose file button.
```
[ ] Yes
[x] No
```

VIH-9497 Upload (non) working hours not working after fixing validation errors

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts

https://tools.hmcts.net/jira/browse/VIH-9518
- Fix an issue where a warning is shown about unsaved changes after saving non-availabilities and navigating away
- Tidy up imports
```
[ ] Yes
[x] No
```

VIH-9518 Fix for unsaved changes prompt after saving non-availabilities

---

AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/security/logout.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/security/logout.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/user-identity.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/user-identity.service.ts

https://tools.hmcts.net/jira/browse/VIH-9621
- Like Video Web, store the cached user profile in a property rather than the session to prevent users from tampering with their roles
- Add spec.ts for the logout component
```
[ ] Yes
[x] No
```

VIH-9621 Store user profile in property instead of session

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/CancelHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetStatusHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetTelephoneConferenceIdTest.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/SearchForAudioRecordedHearingsTests.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs
AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs
AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
AdminWebsite/AdminWebsite/Services/ConferenceDetailsService.cs

https://tools.hmcts.net/jira/browse/VIH-9708
Added optional parameter to GetConferenceDetailsByHearingID, to allow querying of closed hearings. This is to cater for the edge case that a vho is still on the hearing details page of a hearing, just after it closes and they request the telephone conference ID which will return a 404 if the hearing has closed. Should not matter whether or not the hearing has closed in this particular request, as it's only fetching database data (telephone no.)
```
[ ] Yes
[X] No
```

VIH-9708 404 errors on GetTelephoneConferenceIdById endpoint from Admin web api

---

AdminWebsite/AdminWebsite/ClientApp/src/app/shared/menus/case-types-menu/case-types-menu.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/shared/menus/case-types-menu/case-types-menu.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/shared/menus/venues-menu/venues-menu.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/shared/menus/venues-menu/venues-menu.component.ts

https://tools.hmcts.net/jira/browse/VIH-9733
Fixes an error selecting a venue or case type in the dropdown lists. The `items` property is referenced inside the base component, so it needs to be populated here as well
```
[ ] Yes
[x] No
```

VIH-9733 Fix for error selecting venues and case types

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/allocate-hearings/models/allocate-hearing.model.ts

Fixed the issue where ticket was failed in Manual QA , someone forgot to reset hardset code
https://tools.hmcts.net/jira/browse/VIH-9631
This PR addresses the bug fix where i con was not displaying when vho has nonavailability clash . 
```
[ ] Yes
[ x] No
```

VIH-9631 display icon for non availability clash fix 

---

AdminWebsite/AdminWebsite/ClientApp/src/styles.css

https://tools.hmcts.net/jira/browse/VIH-9757
The "Allocate hearings" content on the work allocation page was showing through the "Add a justice user" modal. To resolve this issue, I have increased the z-index of the popup-overlay modal to 2. Longer term, it may be worthwhile to use the Overlay components from the Angular material library as it seems like a more robust solution.

VIH-9757 Allocate hearings content poking through modal dialogs

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts

https://tools.hmcts.net/jira/browse/VIH-9874
Fixes an issue when filtering non-availabilities for a single day in the BST timezone.
The `retrieveDate` function is intended to set the time to midnight, however when passing in a BST date it gets set to 1am. Updates this function to explicitly set the time to midnight.
Also updates the tests to use hyphens rather than slashes in the date format, like the real app.
```
[ ] Yes
[x] No
```

VIH-9874 Fix for non availability filter by date issue with BST dates

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.ts
azure-pipelines.sds.pr-release.yml
azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-9884
- Reverts a previous change to automatically strip special characters (slashes, hyphens etc) out of the endpoint name.
- Fixes a code smell
- Ignores a new SonarCloud rule (https://sonarcloud.io/organizations/hmcts/rules?open=typescript%3AS6544&rule_key=typescript%3AS6544) which is prominent throughout the codebase 
```
[ ] Yes
[x] No
```

VIH-9884 Revert removal of special characters from endpoint name

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/allocate-hearings/allocate-hearings.component.html

https://tools.hmcts.net/jira/browse/VIH-9898
Changes the non-availability clash icon to be centrally aligned, like the other icons
```
[ ] Yes
[x] No
```

VIH-9898 Fix - icons displayed in manual allocation do not align

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant-base/add-participant-base.component.ts

VIH-9924
Somehow an existing user's phone number was invalid and when used in a future booking, the form's add participant button did not appear despite the phone number being invalid. The only way to display the error was to focus on on the field and leave it. Now the form is marked as dirty/touched when pre-populating to ensure the existing values are still considered valid.
```
[ ] Yes
[x] No
```

VIH-9924 form validation for existing user

---

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/RebookHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/packages.lock.json
AdminWebsite/AdminWebsite/AdminWebsite.csproj
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-status-service.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts
AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
AdminWebsite/AdminWebsite/packages.lock.json
charts/vh-admin-web/values.dev.template.yaml

https://tools.hmcts.net/jira/browse/VIH-9950
Changes the functionality of the retry button for a failed booking from confirmHearing to rebookHearing. This will attempt to re-create the conference in video API (along with any users that failed to create) and then poll the booking status to verify that it was created.
The polling is the same as what we use on the summary component to check whether the booking was initially created successfully, so it has been refactored into a common booking status service.
```
[ ] Yes
[x] No
```

VIH-9550 Retry booking should attempt to rebook the conference in video api

---

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.ts

https://tools.hmcts.net/jira/browse/VIH-10041
Added a reset to errors before displaying a new size or invalid file error. Also disabled the upload button if one of these happens, as if you click it, will upload the previous file and potentially show a success message on an invalid file.
```
[ ] Yes
[X] No
```

VIH-10041 Work hours upload error message handling to prevent wrong message being show

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts

https://tools.hmcts.net/jira/browse/VIH-10150
Fixes an issue where the option to record audio is being set to true for the Crime Crown Court case type when adding an interpreter (it should always be false).
```
[ ] Yes
[x] No
```

VIH-10150 Fix for audio recording being set back to true when adding interpreter to Crime Crown Court

---

AdminWebsite/AdminWebsite.UnitTests/Mappers/HearingUpdateRequestMapperTest.cs
AdminWebsite/AdminWebsite/Mappers/HearingUpdateRequestMapper.cs

https://tools.hmcts.net/jira/browse/VIH-10152
Fixes an issue where the Audio Recording Required flag is changed from false to true when editing a booking with an interpreter for the Crime Crown Court or CACD case types. It should always be set to false for these case types.
The logic for whether this flag should be true or false lives in the frontend. However the backend duplicates this and overrides the value in the request if there are interpreters. This is not needed.
```
[ ] Yes
[x] No
```

VIH-10152 Audio recording required being changed to true on edit for Crime Crown Court and CACD

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/BookingListControllerTest.cs
AdminWebsite/AdminWebsite.UnitTests/Controllers/ReferenceDataControllerTests.cs
AdminWebsite/AdminWebsite.UnitTests/Security/UserIdentityTests.cs
AdminWebsite/AdminWebsite/Controllers/BookingListController.cs
AdminWebsite/AdminWebsite/Security/UserIdentity.cs

VIH-10264
Update role checks for CSO & Staff Member

VIH-10264 update the roles allowed to view booking list

---

AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant.model.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.spec.ts
AdminWebsite/AdminWebsite/Controllers/JudiciaryAccountsController.cs

https://tools.hmcts.net/jira/browse/VIH-10297
Dropdown now correctly display the edjudicary accounts searched for in the assign-judge page. This is due to a mapping error, as the do not have contact emails, which is the value displayed in the drop down.

VIH-10297 Fix for ejud accounts not populating in drop down search

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/JudiciaryAccountsControllerTest.cs
AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-details.service.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts
AdminWebsite/AdminWebsite/Controllers/JudiciaryAccountsController.cs
AdminWebsite/AdminWebsite/Mappers/JudgeResponseMapper.cs

https://tools.hmcts.net/jira/browse/VIH-10326
Fixes the admin web issues when the Use Bookings API V2 feature flag is toggled off.
- Error booking a hearing
- Judge name not auto-populating after selecting them on the booking form
The issue was introduced as part of adding the Judicial Office Holders component.
The PostJudgesBySearchTerm endpoint had been removed and the search.service was changed to call a different endpoint which returns a PersonResponse instead of a JudgeResponse. This change was not needed as the search service is not referenced by the Judicial Office Holders component, so I have reverted the service changes and reinstated the original API endpoint and its tests.

VIH-10326 Fix v2 toggle issues

---

AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts

https://tools.hmcts.net/jira/browse/VIH-10363
2 changes needed:
1. Get the judge name from judiciary participants if the judge is booked as a judiciary participant
2. Update `is_judge` and `is_staff_member` to look at the user role name. The case and hearing role are null when V2 is switched on so instead read from user role name, which is populated for both V1 and V2

VIH-10363 Fix judge name disappearing on booking list when V2 switched on

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/JudiciaryAccountsControllerTest.cs
AdminWebsite/AdminWebsite.UnitTests/Mappers/JudgeResponseMapperTest.cs
AdminWebsite/AdminWebsite/Controllers/JudiciaryAccountsController.cs
AdminWebsite/AdminWebsite/Mappers/JudgeResponseMapper.cs

https://tools.hmcts.net/jira/browse/VIH-10362
Mapping judiciary persons to a person response removes the display name property, so don't do this for the V1 ejud judges search - map to a judge response instead

VIH-10362 Fix issue with judge display name not auto populating for ejud and V1 API

---

AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json
AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs
AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs
AdminWebsite/AdminWebsite.UnitTests/Validators/EditHearingRequestValidatorTest.cs
AdminWebsite/AdminWebsite.UnitTests/packages.lock.json
AdminWebsite/AdminWebsite/AdminWebsite.csproj
AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
AdminWebsite/AdminWebsite/Mappers/HearingDetailsResponseMapper.cs
AdminWebsite/AdminWebsite/Validators/EditHearingRequestValidator.cs
AdminWebsite/AdminWebsite/packages.lock.json
charts/vh-admin-web/values.dev.template.yaml

https://tools.hmcts.net/jira/browse/VIH-10361
- Call the new `ReassignJudiciaryJudge` API endpoint to update the judge instead of removing and adding the new judge participants
- Update the `EditHearing` validation to enable the hearing to be edited on V2 when there are no non-judiciary participants
- The `TelephoneParticipants` property has been removed from bookings api, so remove the mapping

VIH-10361 Fix for unable to update judge last minute

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/add-judicial-office-holders/add-judicial-office-holders.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/add-judicial-office-holders/add-judicial-office-holders.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/add-judicial-office-holders/add-judicial-office-holders.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/search-for-judicial-member/search-for-judicial-member.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/search-for-judicial-member/search-for-judicial-member.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/search-for-judicial-member/search-for-judicial-member.component.ts

https://tools.hmcts.net/jira/browse/VIH-10367
1) Added error validation styling to judiciary email and display name fields. 
2) Changed next button text to be dynamic if judicary participant not assigned yet

VIH-10367 Add Judicial Office Holder Validation display

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.html
AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts

https://tools.hmcts.net/jira/browse/VIH-10394
Displays a warning to the user when they are unable to proceed with booking a hearing due to not adding any participants
The `NoParticipantsErrorMsg` const isn't used, so have re-purposed it for this message

VIH-10394 No warning when creating a hearing without participants

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditMultiDayHearingTests.cs
AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
charts/vh-admin-web/values.dev.template.yaml

https://tools.hmcts.net/jira/browse/VIH-10530
The `MapUpdateJudiciaryParticipantsRequestV2` method skips judiciary participants that have not changed in order to avoid an additional call to bookings API when updating hearings. However we don't want to do this for the enhanced update of multi-day bookings, as this is already handled on the bookings API side and results in a bad request from not sending any participants.
Refactor the mapping of existing judiciary participants into a separate method

VIH-10530 Fix - Error for enhanced edit of multi-day booking with no participants

---

AdminWebsite/AdminWebsite/ClientApp/src/app/shared/booking-edit/booking-edit.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/shared/booking-edit/booking-edit.component.ts

https://tools.hmcts.net/jira/browse/VIH-10618
A restriction was previously added to hide the edit hyperlinks on the summary page when editing a multi day booking with the multi day enhancements toggled on, this was because the editing of details had not yet been implemented for the multi-hearing edit.
Now that it has been implemented, this restriction is no longer needed.

VIH-10618 Fix edit links not showing for multi day hearing

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditMultiDayHearingTests.cs
AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
AdminWebsite/AdminWebsite/Mappers/EditMultiDayHearing/HearingRequestMapper.cs
AdminWebsite/AdminWebsite/Models/EditParticipantRequest.cs
AdminWebsite/AdminWebsite/Models/HearingRoleCodes.cs
charts/vh-admin-web/values.dev.template.yaml

VIH-10642
Adding an interpreter forces the audio recording to be required. The update hearing details do not work with the close to start time window, but the domain will update the audio recording required flag when an interpreter is added. Revert to the original audio recording setting to avoid the time clash. This is only an issue because we update hearing details and participants in the same request.

VIH-10642 bug fix adding an interpreter last minute

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant-base/add-participant-base.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts

https://tools.hmcts.net/jira/browse/VIH-10816
- Remove V1 logic from `IsRoleRepresentative` (which uses case role/party). This doesn't work on V2
- Update tests to use V2 roles
- Fix flush error

VIH-10816 Fix for error updating representative

---

AdminWebsite/AdminWebsite.UnitTests/Controllers/UserIdentityControllerTests.cs
AdminWebsite/AdminWebsite/Controllers/UserIdentityController.cs

VIH-10649
Remove redundant Bookings API to get justice user info call in place of using existing claims which already checks for justice user and maps the roles into the ClaimsPrincipal
API call drops from 300ms to 5ms

VIH-10649 Map user roles from claims

---

AdminWebsite/AdminWebsite/ClientApp/.eslintrc.js
AdminWebsite/AdminWebsite/ClientApp/package-lock.json
AdminWebsite/AdminWebsite/ClientApp/package.json
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/other-information/other-information.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/item/participant-item.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/common/guards/change.guard.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-model.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/confirm-delete-popup/confirm-delete-popup.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search/delete-participant-search.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file-cvp/get-audio-file-cvp.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/security/logout.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/security/reform-login.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/security/services/security.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/audio-link-service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-details.service.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/shared/booking-edit/booking-edit.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/testing/data/workhours-allocation-test-data.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/testing/mocks/MockChangesGuard.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/testing/mocks/MockLaunchDarklyService.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/testing/stubs/sign-out-popup-stub.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.spec.ts
AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.spec.ts

VIH-11136
Adding a new ESLint plugin for unused imports and cleaning up unused imports across multiple files.
* Added `eslint-plugin-unused-imports` to the list of plugins in `.eslintrc.js` and configured a rule to flag unused imports as errors.

VIH-11136 remove unused vars and imports add unused imports to lint

---

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/interpreter-form/interpreter-form.component.ts

VIH-11119
remove OnChanges lifecycle hook and optimize change detection

VIH-11119 bugfix selecting interpreter required causes detection change error
