hmcts/vh-admin-web

AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/SauceLabsSettings.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/SeleniumEnvironment.cs
N/A
Added build definition name to identify acceptance tests for corresponding service in Sauce-Lab
```
[ ] Yes
[x] No
```
=> Build definition name for SauceLab settings

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/participant-questionnaire.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnaire.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/styles.css
https://tools.hmcts.net/jira/browse/VIH-4460
Component answer-list-entity and add updated_at field to the model
```
[ ] Yes
[X ] No
```
=> Answer-list entity component layout, add updated date

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/participant-questionnaire.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnaire-api.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnaire.service.spec.ts
https://tools.hmcts.net/jira/browse/VIH-4460
Removed hearing id from the questionnaire model since we don't use it.
```
[ ] Yes
[X] No
```
=> Vih 4460 removing hearingsid

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.spec.ts
n/a
Removed `TestBed` from the breadcrumb tests as it was only adding on dependencies and wasn't being used.
Test speed also improved with ~10s, from 1m 2s to 53s.
```
[ ] Yes
[X] No
```
=> Refactored tests for breadcrumb

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnarie-mapper.ts
https://tools.hmcts.net/jira/browse/VIH-4716
Translate the answers from true/false to Yes/No
```
[ ] Yes
[x ] No
```
=> VIH-4716 - Translate the answers from true/false to Yes/No

AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/address.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/other-information/other-information.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/other-information/other-information.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/config.service.spec.ts
https://tools.hmcts.net/jira/browse/VIH-4712
Added dummy address for add/edit  participants
```
[ ] Yes
[X ] No
```
=> set dummy address

AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts
Fix
Fix persisten the labels confirmed/cancelled on the booking list after return from details to list
```
[ ] Yes
[ X] No
```
=> Persist confirmation/canceled label on the booking list

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts
Fix issue for validation of the judge display name and expand details in Edge
```
[ ] Yes
[ ] No
```
=> Fix display name for judge validation

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataSetUp.cs
=> NOJIRA: remove assert from smoke test

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnaire-api.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnaire-api.service.ts
https://tools.hmcts.net/jira/browse/VIH-4938
If title is not defined, in questionnaire result we should not display the title as undefined.
```
[ ] Yes
[ X] No
```
=> a title should not be displayed as an undefined

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.html
https://tools.hmcts.net/jira/browse/VIH-4939
Display the title label as an optional
```
[ ] Yes
[ X] No
```
=> Title should be labeled as optional

AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.ts
https://tools.hmcts.net/jira/browse/VIH-4941
```
[ ] Yes
[ x] No
```
=> VIH-4941: Adding "Miss" to hard coded titles

AdminWebsite/AdminWebsite/ClientApp/src/app/popups/cancel-popup/cancel-popup.component.html
https://tools.hmcts.net/jira/browse/VIH-4942
```
[ ] Yes
[ ] No
```
=> VIH-4942: Button text change

AdminWebsite/AdminWebsite/ClientApp/src/styles.css
https://tools.hmcts.net/jira/browse/VIH-4379
Fix layout of pop-up
```
[ ] Yes
[X ] No
```
=> Pop-up text align

AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.ts
https://tools.hmcts.net/jira/browse/VIH-4347
Skip to main content link
```
[ ] Yes
[ X] No
```
=> Skip to main content link

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
https://tools.hmcts.net/jira/browse/VIH-4562
Fixed email look up message issue
```
[ ] Yes
[X ] No
```
=> Fixed email look up message issue

AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.html
https://tools.hmcts.net/jira/browse/VIH-4966
fix the outline around the components on the pages in Chrome
```
[ ] Yes
[ X] No
```
=> Take off outline around component on the pages in Chrome

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts
https://tools.hmcts.net/jira/browse/VIH-4926
Fixed Please Select issue
```
[ ] Yes
[X ] No
```
=> Fixed Please Select issue

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
https://tools.hmcts.net/jira/browse/VIH-4972
if email field has less than 3 letters than dont show not found message
```
[ ] Yes
[X ] No
```
=> less than 3 letter in email should not show message not found

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts
https://tools.hmcts.net/jira/browse/VIH-4973
Case type validation.
```
[ ] Yes
[ X] No
```
=> Case type validation

AdminWebsite/AdminWebsite/ClientApp/src/app/shared/unsupported-browser/unsupported-browser.component.html
https://tools.hmcts.net/jira/browse/VIH-4955
Updated text
```
[ ] Yes
[ X] No
```
=> Updated wording

AdminWebsite/AdminWebsite/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-4900
```
[ ] Yes
[x ] No
```
=> VIH-4900: Adding security headers

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/other-information/other-information.component.html
minor fix, take off title from tag text area for other information
```
[ ] Yes
[ X] No
```
=> removed tittle from text area other info

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.css
https://tools.hmcts.net/jira/browse/VIH-4423
```
[ ] Yes
[ ] No
```
=> VIH-4423: Add overflow: hidden

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.ts
https://tools.hmcts.net/jira/browse/VIH-5037
Fixed issue:  appending next portion of data to list create duplicated records. 
```
[ X] Yes
[ ] No
```
=> Fix issue with adding and check for duplication records to booking list

AdminWebsite/AdminWebsite.IntegrationTests/appsettings.json, AdminWebsite/AdminWebsite.UnitTests/ConfigSettingsControllerTests.cs, AdminWebsite/AdminWebsite/Configuration/SecuritySettings.cs, AdminWebsite/AdminWebsite/Controllers/ConfigSettingsController.cs, AdminWebsite/AdminWebsite/appsettings.json
[VIH-5078](https://tools.hmcts.net/jira/browse/VIH-5078)
- Read the redirect uris from config (required by introduction of WAF)
```
[ ] Yes
[x] No
```
=> Add redirect uris to config settings

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts
https://tools.hmcts.net/jira/browse/VIH-5080
```
[ ] Yes
[ ] No
```
=> VIH-5080: Filter/Sort case types

AdminWebsite/AdminWebsite/ClientApp/src/app/app.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/config.service.ts
https://tools.hmcts.net/jira/browse/VIH-4977
Fixed issue with configuration and added more diagnostics
```
[X ] Yes
[ ] No
```
=> Fix issue with settings, add more diagnostics

AdminWebsite/AdminWebsite/Startup.cs
=> Disabled swagger url for production environmet

AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/SeleniumEnvironment.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/AddParticipants.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/Common.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/Summary.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantsSteps.cs, AdminWebsite/AdminWebsite/AdminWebsite.csproj
https://tools.hmcts.net/jira/browse/VIH-5201
Fix for failed smoke tests VHOfficerCreatesHearingWithExistingParticipants and CaseAdminCreatesHearingWithNewParticipants.
```
[ ] Yes
[X] No
```
=> Fixes for failing smoke tests.

AdminWebsite/AdminWebsite.UnitTests/Controllers/SuitabilityControllerTest.cs, AdminWebsite/AdminWebsite/Controllers/SuitabilityAnswersController.cs
=> NOJIRA: Fix when cursor is null

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/representative-questionnarie-mapper.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/suitability-answer.mapper.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/testing/data/suitability-answer-test-data.ts
https://tools.hmcts.net/jira/browse/VIH-5231
Changed suitability answers list to include presenting the case answers
```
[ X] Yes
[ ] No
```
=> Change Suitability answers list to include presenting the case answers

AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
=> NOJIRA: Fixing Cursor

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/individual-questionnarie-mapper.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/representative-questionnarie-mapper.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/suitability-answer.mapper.ts
https://tools.hmcts.net/jira/browse/VIH-5379
Changed wording for presenting the case question
```
[ ] Yes
[X ] No
```
=> Changed wording for presenting the case question

AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingConfirmation.feature
N/A
Removed smoketest tag from the failing test
```
[ ] Yes
[ x] No
```
=> Removed smoketest tag

AdminWebsite/AdminWebsite.AcceptanceTests/Data/DateFormats.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs
- Fix for an issue where data formats were being returned without a trailing zero
```
[ ] Yes
[X] No
```
=> Added a fix for date format issues

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/OtherInformationSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
- Fixed causes of failed edit hearing details and edit hearing schedule tests
```
[ ] Yes
[X] No
```
=> Fixed causes of failed edit hearing details and edit hearing schedule tests

AdminWebsite/AdminWebsite.AcceptanceTests/Data/Test.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
- Users that had been added, but the test had not reached the point of submitting were failing when trying to delete users that didn't exist in AAD. 
```
[ ] Yes
[X] No
```
=> Fixed a bug with new user cleanup

AdminWebsite/AdminWebsite.AcceptanceTests/Configuration/AdminWebConfig.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/TestContext.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingsListSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BrowserSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/CancelHearingTests.cs
- Removed unused code
- Moved UserAccounts to parent
```
[ ] Yes
[X] No
```
=> Removed unused code, moved UserAccounts

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Data/HearingRequestBuilder.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/useraccounts.json, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
- Updated automation NuGet package
- Editted the hearing request to include not sending questionnaires
- Updated spec flow
- Updated video api client
```
[ ] Yes
[X] No
```
=> Updated hearing request and nuget package

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
- Fixed a test
- Moved some requests to acceptance test project
```
[ ] Yes
[X] No
```
=> Fix for cancel test

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts
https://tools.hmcts.net/jira/browse/VIH-5514
If not send questionnaires is null, set it to false 
```
[ X] Yes
[ ] No
```
=> VIH-5514 fix send questionnary  is null error

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-5506
Fix to update judge display name
```
[ ] Yes
[ ] No
```
=> Fix to update judge display name

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking-confirmation/booking-confirmation.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking-confirmation/booking-confirmation.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking-confirmation/booking-confirmation.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking-confirmation/booking-confirmation.component.ts
https://tools.hmcts.net/jira/browse/VIH-5462
Navigate to booking details from confirmation page
```
[ ] Yes
[x ] No
```
=> Navigate to booking details from confirmation page

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/CommonSteps.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.html
https://tools.hmcts.net/jira/browse/VIH-5233
- added a role for the skip div.
- added title for the sign out nav element.
- updated acceptance test nuget package to run on safari.
```
[ ] Yes
[x] No
```
=> VIH-5233:[Admin Web | Accessibility] All pages should be contained within landmarks

AdminWebsite/AdminWebsite/ClientApp/package.json
https://tools.hmcts.net/jira/browse/VIH-5537
```
[ ] Yes
[ ] No
```
=> VIH-5537: revert adal-angular package version

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.html
https://tools.hmcts.net/jira/browse/VIH-5233
- removed main container from dashboard component
- added h1 title for the bookings list page.
```
[ ] Yes
[x] No
```
=> VIH-5233: [Admin Web | Accessibility] All pages should be contained within landmarks

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj
- Updated name on overnight release names
```
[ ] Yes
[X] No
```
=> Update overnight tests release name

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Data/DateFormats.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.Services.Generator/video-api-csharp.nswag, AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/VideoWeb.Services/VideoApiClient.cs
- Updated NSwag config for video api and upgraded NuGet
```
[ ] Yes
[X] No
```
=> Updated NSwag config for video api and upgraded NuGet

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingConfirmationSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingsListSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/CommonSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/DashboardSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/ErrorSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/LoginSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/OtherInformationSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
- Update to test Safari
```
[ ] Yes
[X] No
```
=> Update to latest safari

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/OtherInformationSteps.cs
- Added a step to tab to an element, as the changes to button clicks causes the click to order before page is loaded fully
```
[ ] Yes
[X] No
```
=> VIH-5255 Workaround fixes for edit tests

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/OtherInformationSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, CODEOWNERS
- Fixes for the 2 failing overnight tests
```
[ ] Yes
[X] No
```
=> Added fixes for failing Edit tests

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Data/DateFormats.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BrowserSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
- Added a fix for the changes in date format in sauce labs
- Updated NuGet package
```
[ ] Yes
[X] No
```
=> Added a fix for the changes in date format in saucelabs

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Data/DateFormats.cs
-  Added a fix for a date format issue whereby the executor is running i…n the UK, but sauce labs is in the EU
```
[ ] Yes
[X] No
```
=> Added a fix for a date format issue

AdminWebsite/AdminWebsite.UnitTests/Controllers/HealthTests.cs, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Controllers/HealthCheckController.cs, AdminWebsite/AdminWebsite/Models/HealthCheckResponse.cs
- added property to health check to return application version
https://tools.hmcts.net/jira/browse/VIH-5629
- added property to health check to return application version
```
[ ] Yes
[x] No
```
=> VIH-5629: Add version property to healthcheck endpoint or new endpoint

.githooks/pre-commit, .githooks/prepare-commit-msg, README.md
https://tools.hmcts.net/jira/browse/VIH-5605
added git hooks to validate branch name and commit message
```
[X ] Yes
[ ] No
```
=> feature/VIH-5605 : added git hooks to validate branch name and commits

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking-confirmation/booking-confirmation.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking-confirmation/booking-confirmation.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.ts
https://tools.hmcts.net/jira/browse/VIH-5660
Review code and unsubscribe all not closed subscriptions
```
[X ] Yes
[ ] No
```
=> feature/VIH-5660 : unsibscribe all not closed subscriptions

.githooks/pre-commit, .githooks/prepare-commit-msg, AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Data/HearingRequestBuilder.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Data/TestData/DefaultDataManager.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DriverHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/HealthcheckHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/HooksSequence.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite.UnitTests/Security/TokenProviderTests.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs, AdminWebsite/AdminWebsite/Program.cs
- Fixes for Conferences for today changes
```
[ ] Yes
[X] No
```
=> VIH-5552 Fixes for Conferences for today changes

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DriverHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/HooksSequence.cs
- Removed sign out hooks 
```
[ ] Yes
[X] No
```
=> VIH-5255 Removed sign out hooks

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DriverHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/HooksSequence.cs
=> VIH-5255 Stop Edge Chromium locaclly only

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participants-list/participants-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.html
https://tools.hmcts.net/jira/browse/VIH-5383
```
[ ] Yes
[ ] No
```
=> VIH-5383 Change participant type Solicitor to Representative

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participants-list/participants-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant.model.ts
https://tools.hmcts.net/jira/browse/VIH-5383
```
[ ] Yes
[ ] No
```
=> VIH-5383 Fix edit participant screen

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts
https://tools.hmcts.net/jira/browse/VIH-5536
Added validation for hearing duration
```
[ ] Yes
[ x] No
```
=> VIH-5536 Fix for hearing duration validation

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking.service.ts
https://tools.hmcts.net/jira/browse/VIH-5756
return back to summary page after edit
```
[X ] Yes
[ ] No
```
=> VIH-5756 back to summary after edit

AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/cancel-booking-popup/cancel-booking-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/styles.css
https://tools.hmcts.net/jira/browse/VIH-3991
- added a ui fix to left align the error messages
```
[ ] Yes
[x] No
```
=> VIH-3991 Cancel-popup-bug-fix

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DriverHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs
https://tools.hmcts.net/jira/browse/VIH-5703
- Added waits for the dropdown page to be populated before attempting to select
```
[ ] Yes
[X] No
```
=> VIH-5703 Added waits for Assign Judge page

AdminWebsite/AdminWebsite/ClientApp/angular.json, AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/cancel-booking-popup/cancel-booking-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/cancel-booking-popup/cancel-booking-popup.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/cancel-booking-popup/cancel-booking-popup.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/scripts/init-script.js, AdminWebsite/AdminWebsite/ClientApp/src/styles.css
https://tools.hmcts.net/jira/browse/VIH-3991
- added character count in UI.
- separate messages from max lenght and required validations.
```
[ ] Yes
[x] No
```
=> VIH-3991 cancel popup bug fix

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts
https://tools.hmcts.net/jira/browse/VIH-5799
- reset the hearing types on change of case types.
```
[ ] Yes
[x] No
```
=> VIH-5799 hearing type error

AdminWebsite/AdminWebsite.AcceptanceTests/Pages/BookingDetailsPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/BookingsListPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/SummaryPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingsListSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/booking-list.model.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/bookings-list.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-details.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.spec.ts
https://tools.hmcts.net/jira/browse/VIH-5792
- updated to display Case Type
```
[ ] Yes
[x] No
```
=> VIH-5792 Case_type_not_displaying_in_Booking_details

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts
https://tools.hmcts.net/jira/browse/VIH-5810
The audio recording options should be not available for confirmed booking.
```
[ X] Yes
[ ] No
```
=> VIH-5810 Disable audio options for confirmed booking

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html
VIH-5830
- fixed issue in bookings list page for cancelled hearing
```
[ ] Yes
[x] No
```
=> VIH-5830 accessibility_issue_booking_details

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html
https://tools.hmcts.net/jira/browse/VIH-5835
- removed details section.
```
[ ] Yes
[x] No
```
=> VIH-5835 Remove_the_Details_section_on_Assign_Judge_page

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Features/AddParticipants.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingDetails.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/HearingDetails.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/HearingSchedule.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/Login.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/OtherInformation.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/Questionnaire.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/Summary.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DriverHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BrowserSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/OtherInformationSteps.cs, AdminWebsite/AdminWebsite.IntegrationTests/Controllers/ConfigSettingsControllerTests.cs, AdminWebsite/AdminWebsite.IntegrationTests/Services/ApplicationLoggerTests.cs, AdminWebsite/AdminWebsite.IntegrationTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
https://tools.hmcts.net/jira/browse/VIH-5856
- Added extended smoketest tags for beta pipelines
- Fixed edit tests
```
[ ] Yes
[X] No
```
=> VIH-5856 Added extended smoketest tags

AdminWebsite/AdminWebsite/ClientApp/.editorconfig, AdminWebsite/AdminWebsite/ClientApp/.prettierrc, AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.ts
https://tools.hmcts.net/jira/browse/VIH-5920
```
[ ] Yes
[ ] No
```
=> VIH-5920 Change user password fix

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Features/ChangePassword.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/ChangePasswordPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/Journeys/ChangePasswordJourney.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/Journeys/Journey.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/Page.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/ChangePasswordSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/DashboardSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/ProgressionSteps.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs, CODEOWNERS
- Added a password reset acceptance test
```
[ ] Yes
[X] No
```
=> VIH-5416 Added acceptance tests for Reset Password feature

AdminWebsite/AdminWebsite.AcceptanceTests/Features/Login.feature
- Remove test replaced by change password test
```
[ ] Yes
[X ] No
```
=> VIH-5255 Remove test replaced by change password test

AdminWebsite/AdminWebsite.AcceptanceTests/Features/AddParticipants.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/AddPartcipantsPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
- https://tools.hmcts.net/jira/browse/VIH-4194
- Added Reform Email acceptance test
```
[ ] Yes
[X] No
```
=> VIH-4194 Added Reform Email acceptance test

AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonsControllerTest.cs, AdminWebsite/AdminWebsite/Controllers/PersonsController.cs
https://tools.hmcts.net/jira/browse/VIH-5929
Added filter to remove contact emails ending with hmcts
```
[ ] Yes
[ x] No
```
=> VIH-5929 Added fIlter to remove contact emails ending with hmcts

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
https://tools.hmcts.net/jira/browse/VIH-5686
Select role moved screen down
```
[ X] Yes
[ ] No
```
=> VIH-5686 select role moved screen down

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts
https://tools.hmcts.net/jira/browse/VIH-5703
Fix bug on schedule page, valueChanges of null object
```
[ X] Yes
[ ] No
```
=> VIH-5703 Fix valueChanges of null object

AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.scss
https://tools.hmcts.net/jira/browse/VIH-5957
- fix for accessibility error.
```
[ ] Yes
[x] No
```
=> VIH-5957 Admin_Web Dashboard_accessibility_issue

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetHearingsByCaseNumberTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-5961
```
[ ] Yes
[ ] No
```
=> VIH-5961 Decode the param caseNumber

AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-5961
```
[ ] Yes
[ ] No
```
=> VIH-5961 Change caseNumber to FromQuery and not from route

AdminWebsite/AdminWebsite.UnitTests/Controllers/HealthTests.cs, AdminWebsite/AdminWebsite/Controllers/HealthCheckController.cs, AdminWebsite/AdminWebsite/Models/HealthCheckResponse.cs
https://tools.hmcts.net/jira/browse/VIH-5970
```
[ ] Yes
[ ] No
```
=> VIH-5970 Add health check for video api

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnaire.service.ts
https://tools.hmcts.net/jira/browse/VIH-5969
Limit records for questionnaire set to 200
```
[ X] Yes
[ ] No
```
=> VIH-5969 Increase limit records for questionnaire

AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-link-button/get-audio-link-button.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/hearing-search-results/hearing-search-results.component.html
https://tools.hmcts.net/jira/browse/VIH-5993
audio link valid for 14 days, removed error msg for search audio button
```
[ ] Yes
[ ] No
```
=> VIH-5993 audio link valid for 14 days

AdminWebsite/AdminWebsite.AcceptanceTests/Features/TestHelpers.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/TestHelperSteps.cs
- Add a helper class for manual testing
```
[ ] Yes
[X] No
```
=> VIH-5255 Add a helper class for manual testing

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Features/GetAudioFile.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/TestHelpers.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/GetAudioFilePage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/GetAudioFileSteps.cs
- Added a fix for audio recording test
```
[ ] Yes
[X] No
```
=> VIH-5255 Added a fix for audio recording test

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingDetails.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/TestContext.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/GetAudioFileSteps.cs
- Fixes for 2 failing overnight tests
```
[ ] Yes
[X] No
```
=> VIH-5255 Fixes for tests

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj
- Fix to an audio recoding filepath issue
```
[ ] Yes
[X] No
```
=> VIH-5255 Filepath fix

AdminWebsite/AdminWebsite.UnitTests/Controllers/AudioPlatformControllerTests.cs, README.md
https://tools.hmcts.net/jira/browse/VIH-6086
- Updated readme instructions with Stryker run
```
[ ] Yes
[x] No
```
=> VIH-6086 Updated readme instructions with Stryker run

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.html
https://tools.hmcts.net/jira/browse/VIH-5785
=> VIH-5785 Change audio recording allowed to edit

AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/hearing-search-results/hearing-search-results.component.html
https://tools.hmcts.net/jira/browse/VIH-6061
Removed 'reference' on Get Audio File Link page
```
[ ] Yes
[x ] No
```
=> VIH-6061 Replace case reference with case number

AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-link-button/get-audio-link-button.component.html
https://tools.hmcts.net/jira/browse/VIH-6123
=> VIH-6123 Change valid from 14 days to 7 days text

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.html
https://tools.hmcts.net/jira/browse/VIH-6101
Change button wording to Confirm booking
```
[X ] Yes
[ ] No
```
=> VIH-6101 Change button value to Confirm booking

AdminWebsite/AdminWebsite/Controllers/ReferenceDataController.cs
https://tools.hmcts.net/jira/browse/VIH-5662
Removed the encoding for get
```
[ ] Yes
[ x] No
```
=> VIH-5662 Remove encoding

azure-pipelines.nightly.yml, azure-pipelines.release.yml
VIH-5936
fix mistake with nightly and CD triggers
```
[ ] Yes
[x] No
```
=> VIH-5936 fix nightly cd trigger

AdminWebsite/AdminWebsite.IntegrationTests/Controllers/ConfigSettingsControllerTests.cs, azure-pipelines.beta.yml, azure-pipelines.nightly.yml
- Nightly build was accidentally running Chrome/Mac as unsupported
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for nightly tests

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts
https://tools.hmcts.net/jira/browse/VIH-5814
Validate time and date in the past
```
[ X] Yes
[ ] No
```
=> VIH-5814 validate date time in past

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/TestContext.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DriverHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/HooksSequence.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, azure-pipelines.beta.yml
- Fix for timezone issues
- FIx for beta job timings
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for time issue and beta build

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
- Fix for more datetime issues on the overnights
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for more datetime issues

azure-pipelines.beta.yml, azure-pipelines.nightly.yml
- Updated Admin Web nightly to run at 7pm and beta build to run at 5pm
```
[ ] Yes
[X] No
```
=> VIH-5255 Rescheduled build times

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/GetAudioFileSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
- Potential fix for regular timeout issues
- Fix for Get Audio Link test
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for WebDriver timeouts

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
- Retry mechanism for failed browser launch
```
[ ] Yes
[X] No
```
=> VIH-5255 Retry mechanism for failed browser launch

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
- Updated the retry mechanism
```
[ ] Yes
[X] No
```
=> VIH-5255 Moved navigate to url to NgDriver from Wrapped Driver 

AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts
https://tools.hmcts.net/jira/browse/VIH-5617
feature/VIH-5617 : Removed address fields from response object
```
[ ] Yes
[x ] No
```
=> VIH-5617 Removed address fields from response object

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html
https://tools.hmcts.net/jira/browse/VIH-6294
Display 'Failed' status in booking list
```
[ ] Yes
[ x] No
```
=> VIH-5867 Added failed status

azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
=> VIH-6286 add support across all pipelines for better FW await

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/GetAudioFileSteps.cs
- Test is still failing, but its now updated to reflect the new requirements
```
[ ] Yes
[X] No
```
=> VIH-5255 get audio file test fix

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/other-information/other-information.component.html
https://tools.hmcts.net/jira/browse/VIH-6405
- updates to cancel button
```
[ ] Yes
[x] No
```
=> VIH-6405 pressing cancel takes the user to the following screen

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts
https://tools.hmcts.net/jira/browse/VIH-6243
- changed the representative check to include Prosecution, Defence Advocate, Prosecution Advocate
```
[ ] Yes
[x] No
```
=> VIH-6243 add new case hearing types and roles for cacd

AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search/delete-participant-search.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-delete-service.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-delete-service.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/test.ts
VIH-6274
* open hearing from deletion search results list
* change tile for delete participant to pink
* remove venue name from results list
* use location back when on booking to return to delete participant page or booking list based on route
---
---
```
[ ] Yes
[x] No
```
=> VIH-6274 open hearing from deletion search results

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/copy-sip/copy-sip.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/copy-sip/copy-sip.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/copy-sip/copy-sip.component.ts
https://tools.hmcts.net/jira/browse/VIH-6312
- appended pin to the sip address for copy sip component.
```
[ ] Yes
[x] No
```
=> VIH-6312 VHO saves hearing with Video access points added append pin

.angulardoc.json, .gitignore, AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs, AdminWebsite/AdminWebsite.IntegrationTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonsControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.UserAPI.Client/UserApiClient.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/confirm-delete-popup/confirm-delete-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/confirm-delete-popup/confirm-delete-popup.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/confirm-delete-popup/confirm-delete-popup.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search/delete-participant-search.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search/delete-participant-search.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search/delete-participant-search.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-delete-service.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-delete-service.service.ts, AdminWebsite/AdminWebsite/Controllers/PersonsController.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs, azure-pipelines.yml
VIH-6275
delete participant
```
[ ] Yes
[x] No
```
=> VIH-6275 delete participant

AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs
https://tools.hmcts.net/jira/browse/VIH-6469
- Nswag update bookingapiClient
```
[ ] Yes
[x] No
```
=> VIH-6469 unable_to_edit_a_booking

AdminWebsite/AdminWebsite.AcceptanceTests/Pages/DeleteUserPage.cs, AdminWebsite/AdminWebsite.UnitTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-hearing-delete-result-model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.html, AdminWebsite/AdminWebsite/Services/UserAccountService.cs
VIH-5621
*  display venue name in search results
* check user role is not judge or VHO before deleting in AD
```
[ ] Yes
[x] No
```
=> VIH-5621 delete user

AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonsControllerTest.cs, AdminWebsite/AdminWebsite/Controllers/PersonsController.cs
VIH-6491
* unauthorised users for deletion (i.e. not individual or rep) cannot be deleted
```
[ ] Yes
[x] No
```
=> VIH-6491 capture unauthorised user responses to be deleted

AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.ts
VIH-6506
Cloud room for cvp search should be a number
```
[ X] Yes
[ ] No
```
=> VIH-6506 cloud room should be number

AdminWebsite/AdminWebsite.AcceptanceTests/Data/HearingRequestBuilder.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/ChangePasswordSteps.cs
https://tools.hmcts.net/jira/browse/VIH-6268
- Fixes for overnight tests following integration changes with Test Api
```
[ ] Yes
[x] No
```
=> VIH-6268 Fixes for overnights

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
- Tests currently have an issue where they sit on the Assign Judge screen for around 1 min before continuing. This is a fix for that. 
```
[ ] Yes
[X] No
```
=> VIH-5255 Speed up Judge Selection on tests

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
- (Changes in the NuGet project)
```
[ ] Yes
[X] No
```
=> VIH-5255 Stop AAD being hammered

AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.html
https://tools.hmcts.net/jira/browse/VIH-6506
Change error message for cloud room
```
[ ] Yes
[X ] No
```
=> VIH-6506 Change error message for cloud room

.gitignore, AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Properties/AssemblyInfo.cs, AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs
- https://tools.hmcts.net/jira/browse/VIH-6544
- Enable test parallel execution
```
[ ] Yes
[x] No
```
=> VIH-6544 Enable test parallel execution

AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/confirm-delete-popup/confirm-delete-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/styles.css
https://tools.hmcts.net/jira/browse/VIH-6492
Fix overlay of confirmation popup to delete account
```
[ ] Yes
[ X] No
```
=> VIH-6492 confirm popup delete account overlay

AdminWebsite/AdminWebsite.AcceptanceTests/Features/AddParticipants.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/AssignJudge.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingConfirmation.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingDetails.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingsList.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/Dashboard.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/HearingDetails.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/HearingSchedule.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/Login.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/OtherInformation.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/Summary.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/VideoAccessPoints.feature
- Ignored Case Admin tests
```
[ ] Yes
[X] No
```
=> VIH-5255 Ignored Case Admin tests

AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs
VIH-6550
Assign defence advocate to professional user group
```
[ ] Yes
[x] No
```
=> VIH-6550 Assign defence advocate to professional user group

AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/package.json
https://tools.hmcts.net/jira/browse/VIH-6552
- reverted zone-js to 0.10.3 from 0.11.0 to get IE 11 working.
```
[ ] Yes
[x ] No
```
=> VIH-6552 Cannot_get_configuration_settings_on_Internet_Explorer

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/hearing.model.ts
https://tools.hmcts.net/jira/browse/VIH-6281
Multi days hearing changes for UI
```
[ ] Yes
[ ] No
```
=> VIH-6281 multi days hearing ui

AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.ts
https://tools.hmcts.net/jira/browse/VIH-6530
=> VIH-6530 change password input to keep email

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts, azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-6583
Hide multi day for booked hearing
```
[ X] Yes
[ ] No
```
=> VIH-6583 hide multi day box

AdminWebsite/AdminWebsite.UnitTests/Helper/DateListMapperTest.cs, AdminWebsite/AdminWebsite/Helper/DateListMapper.cs
https://tools.hmcts.net/jira/browse/VIH-6604
Fix multi day hearing
```
[X ] Yes
[ ] No
```
=> VIH-6604 Fix for multi dates hearing

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/get-audio-file.component.ts, AdminWebsite/AdminWebsite/Contracts/Queries/SearchForAudioRecordedHearingsQuery.cs
VIH-6190
* add search by date
```
[ ] Yes
[x] No
```
=> VIH-6190 add search by date

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs
- Random allocation wait for parallel execution workaround
- Added fix for case name issue on multi day hearings
```
[ ] Yes
[X] No
```
=> VIH-5255 Random allocation wait for parallel execution workaround

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
VIH-6618
keep 'user will be created' message on screen after text field loses focus
```
[ ] Yes
[x] No
```
=> VIH-6618 leave new account created message on screen

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BrowserSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
- Fix for parallel execution issues
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for parallel execution issues

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/HealthcheckHooks.cs
- Retry on forbidden
```
[ ] Yes
[X] No
```
=> VIH-5255 Retry on forbidden

AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-6639
=> VIH-6639 increase_confirmation_retries

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingConfirmationSteps.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
- Case name contains fix
```
[ ] Yes
[X] No
```
=> VIH-5255 Case name contains fix

AdminWebsite/AdminWebsite.IntegrationTests/AdminWebsite.IntegrationTests.csproj, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonController/DeletePersonWithUsernameTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonsControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Controllers/PersonsController.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-6275
* also search in AD when searching for participants to delete
* on create hearing, explicitly search for contact before creating an account for new participants
```
[ ] Yes
[x] No
```
=> VIH-6275 include users in AD in search when deleting

AdminWebsite/AdminWebsite/ClientApp/src/app/popups/confirmation-popup/confirmation-popup.component.html
https://tools.hmcts.net/jira/browse/VIH-6284
Fixed Popup issue for duplicate user
```
[ ] Yes
[ x] No
```
=> VIH-6284 Popup issue for duplicate user

AdminWebsite/AdminWebsite.AcceptanceTests/Pages/BookingDetailsPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-participant-list/booking-participant-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-details.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-details.service.ts
https://tools.hmcts.net/jira/browse/VIH-6666
Display participant phone number
```
[ X] Yes
[ ] No
```
=> VIH-6666 show participant phone number

AdminWebsite/AdminWebsite.UnitTests/Controllers/BookingListControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/CancelHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/SearchForAudioRecordedHearingsTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs, AdminWebsite/AdminWebsite/Controllers/BookingListController.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-6671
Fix save booking after update when participant was removed and again added.
```
[ X] Yes
[ ] No
```
=> VIH-6671 fix unable save booking if participants were removed

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-6649
- fix for defence advocate, changed to search by username
```
[ ] Yes
[x] No
```
=> VIH-6649 cannot create cacd hearing with existing user

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.html
https://tools.hmcts.net/jira/browse/VIH-6666
Add space between lines in participant details
```
[ ] Yes
[X ] No
```
=> VIH-6666 add space between lines

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
https://tools.hmcts.net/jira/browse/VIH-6677
- updated to populate first name, last name, on blur,  if participant found based on email
```
[ ] Yes
[x] No
```
=> VIH-6677 VHO_can_overwrite_existing_email_account_causing_booking_to_error 

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
https://tools.hmcts.net/jira/browse/VIH-6677
- updated check for selected email.
```
[ ] Yes
[x] No
```
=> VIH-6677 vho can overwrite existing email account causing booking to error

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts
https://tools.hmcts.net/jira/browse/VIH-6514
Fix cannot navigate from participant page to next page if no participant were added.
Fix assign judge page can navigate.
```
[X ] Yes
[ ] No
```
=> VIH-6514 fix to create hearing without the participants

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/participant-details/participant-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/case-roles.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.ts
https://tools.hmcts.net/jira/browse/VIH-6659
- updated to display case roles in the booking details screen. (for witness, LIP and representative participant hearing roles)
```
[ ] Yes
[x] No
```
=> VIH-6659 vho sees case role in participant list on booking details

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.ts
https://tools.hmcts.net/jira/browse/VIH-6702
- removed validation for duplicate app/respondent  advocates
```
[ ] Yes
[x] No
```
=> VIH-6702 VHO_links_Advocate_to_more_than_one_endpoint

AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/answer-list-entry/answer-list-entry.component.ts
https://tools.hmcts.net/jira/browse/VIH-6388
Suppress not answered questions for individual in questionnaire report
```
[X ] Yes
[ ] No
```
=> VIH-6388 supress not answered questions for individual

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
- Removed questionnaire change
```
[ ] Yes
[X] No
```
=> VIH-5255 Removed questionnaire change

azure-pipelines.release.yml
VIH-6736
* point sandbox to kinly dev
```
[x] Yes
[] No
```
=> VIH-6736 point sandbox to kinly dev

azure-pipelines.release.yml
VIH-6736 
add missing env variable
```
[ ] Yes
[x] No
```
=> VIH-6736 add missing env variable

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertConference.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingDetails.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/BookingsListPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingsListSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
https://tools.hmcts.net/jira/browse/VIH-6742
- Added verification for conference on confirm 
- and expanded multi day hearing verification
```
[ ] Yes
[X] No
```
=> VIH-6742 Added verification for conference on confirm 

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
- Fix for single day weekend smoke test
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for single day weekend smoke test

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertConference.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs
- Removed contact email check for judges
```
[ ] Yes
[X] No
```
=> VIH-5255 Removed contact email check for judges

AdminWebsite/AdminWebsite.AcceptanceTests/Configuration/AdminWebConfig.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Configuration/AdminWebVhServiceConfig.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Configuration/KinlyConfiguration.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite/Startup.cs, azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-6854
Add variable Conference phone in the group KinlyConfiguration (pipeline)
```
[ X] Yes
[ ] No
```
=> VIH-6854 Add phone to kinly config group pipeline

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs
- Updated Test Api Client and packages
```
[ ] Yes
[X] No
```
=> VIH-6690 Updated Test Api Client and packages

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetTelephoneConferenceIdTest.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
VIH-6854
If conference is closed, don't display phone conference Id and phone
```
[X ] Yes
[ ] No
```
=> VIH-6854 fix phone Id for closed conference

AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-6711
=> VIH-6711 increase_confirm_retry

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertConference.cs, AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs
- Fix for Endpoint Assertion
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for Endpoint Assertion

AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.html
https://tools.hmcts.net/jira/browse/VIH-5831
Space between logo and title in the header
```
[ ] Yes
[ ] No
```
=> VIH-5831 space between logo and title

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
https://tools.hmcts.net/jira/browse/VIH-6880
Validation for contact email in add participant for domain and top domain.
```
[ ] Yes
[ ] No
```
=> VIH-6880 regex changed to validate top domain

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
https://tools.hmcts.net/jira/browse/VIH-6738
=> VIH-6738 Add representative to the hearing role lookup

AdminWebsite/AdminWebsite.AcceptanceTests/Data/HearingRequestBuilder.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Features/Login.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/Users.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs, AdminWebsite/AdminWebsite.UnitTests/.config/dotnet-tools.json, AdminWebsite/AdminWebsite.UnitTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs
https://tools.hmcts.net/jira/browse/VIH-6767
Add Winger and PM to JOH AAD group
```
[X ] Yes
[ ] No
```
=> VIH-6767 add ad group for JOH

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs
https://tools.hmcts.net/jira/browse/VIH-6894
=> VIH-6894 Adding retry to the AAD user adding to group

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
https://tools.hmcts.net/jira/browse/VIH-6997
=> VIH-6997 BUG clear participant Admin web

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts
https://tools.hmcts.net/jira/browse/VIH-6945
Fix for Blank Booking Details screen
```
[ ] Yes
[x ] No
```
=> VIH-6945 Fix for Blank Booking Details screen

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonsControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/Extensions/ConferenceDetailsResponseExtensionsTests.cs, AdminWebsite/AdminWebsite.UnitTests/Extensions/UserProfileExtensionsTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.UnitTests/stryker-config.json, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Extensions/ConferenceDetailsResponseExtensions.cs, AdminWebsite/AdminWebsite/Extensions/UserProfileExtensions.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs
https://tools.hmcts.net/jira/browse/VIH-5602
- Fixed mutation test issues
```
[ ] Yes
[x] No
```
=> VIH-5602 Mutation issue fix

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/appsettings.json, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.AcceptanceTests/parameters.runsettings
https://tools.hmcts.net/jira/browse/VIH-7058
- Switch to change test execution environment
- Switch to execute on sauce labs from local
```
[ ] Yes
[X] No
```
=> VIH-7058 switches to change environment and sauce labs execution

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-7058
- adding in an exception when test secrets not present
```
[ ] Yes
[X] No
```
=> VIH-7058 Adding in exception when no test secrets present

AdminWebsite/.dockerignore, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.Services.Generator/AdminWebsite.Services.Generator.csproj, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/.dockerignore, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Dockerfile, AdminWebsite/AdminWebsite/Program.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-7173
Add new configuration provider for SDS
https://hmctsreform.visualstudio.com/VirtualHearings/_build/results?buildId=27909&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a
```
[ ] Yes
[ ] No
```
=> VIH-7173 add new configuration provider for sds

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Program.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-7173
Update usage of AddAksKeyVaultSecretProvider
```
[ ] Yes
[x] No
```
=> VIH-7173 Update usage of AddAksKeyVaultSecretProvider

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.ts
https://tools.hmcts.net/jira/browse/VIH-7090
added logger and format date from string
```
[X ] Yes
[ ] No
```
=> VIH-7090 added logger and format date

AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant/edit-participant.component.html
VIH-6162
add labels for first and name when editing a participant
```
[ ] Yes
[x] No
```
=> VIH-6162 add labels for first and name when editing a participant

AdminWebsite/AdminWebsite.IntegrationTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/UserDataControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/AddNotificationRequestMapperTest.cs, AdminWebsite/AdminWebsite.UnitTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/change-password/change-password.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/user-data.service.ts, AdminWebsite/AdminWebsite/Contracts/Responses/UpdateUserPasswordResponse.cs, AdminWebsite/AdminWebsite/Controllers/UserDataController.cs, AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-7005
* Send password reset emails
* Stop displaying new passwords on the UI
```
[ ] Yes
[x] No
```
=> VIH-7005 password reset notification

AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.html
- https://tools.hmcts.net/jira/browse/VIH-5552
- update to alt text of edit participant name
```
[ ] Yes
[X] No
```
=> VIH-5552 Change to alt text of 'Edit participant name'

AdminWebsite/AdminWebsite.AcceptanceTests/Features/EditParticipantName.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/EditParticipantNamePage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/EditParticipantNameSteps.cs, AdminWebsite/AdminWebsite.BookingsAPI.Client/BookingsApiClient.cs, AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonController/GetPersonForUpdateByContactEmailTests.cs, AdminWebsite/AdminWebsite.VideoAPI.Client/VideoApiClient.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant-search-results/edit-participant-search-results.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant-search-results/edit-participant-search-results.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant-search-results/edit-participant-search-results.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant-search/edit-participant-search.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant-search/edit-participant-search.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant-search/edit-participant-search.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-edit-service.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-edit-service.service.ts, AdminWebsite/AdminWebsite/Controllers/PersonsController.cs
VIH-6162
* allow the search to edit to include JOHs
* display a message when searching for participants not allowed for editing
```
[ ] Yes
[x] No
```
=> VIH-6162 allow the search to edit to include johs

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite/ClientApp/package-lock.json
https://tools.hmcts.net/jira/browse/VIH-5552
- Removed workaround for parallel test execution
```
[ ] Yes
[X] No
```
=> VIH-5552 Remove Parallel Test Execution Workaround

AdminWebsite/AdminWebsite.AcceptanceTests/Features/ChangePassword.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/ChangePasswordPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/ChangePasswordSteps.cs
https://tools.hmcts.net/jira/browse/VIH-5552
- fix to change password test
```
[ ] Yes
[X] No
```
=> VIH-5552 Fix to change password test

AdminWebsite/AdminWebsite.AcceptanceTests/Features/EditParticipantName.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/EditParticipantNamePage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/EditParticipantNameSteps.cs
https://tools.hmcts.net/jira/browse/VIH-6162
-- Updated Edit participant name scenarios
```
[ ] Yes
[x] No
```
=> VIH-6162 update participant name scenario

AdminWebsite/AdminWebsite/Extensions/ConfigureServicesExtensions.cs
VIH-6162
Init Video API Client factory
```
[ ] Yes
[x] No
```
=> VIH-6162 Init VideoAPI client using GetClient factory

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Helper/HearingResponseBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-7300
- Added HearingResponseBuilder
```
[ ] Yes
[x] No
```
=> VIH-7300 Added HearingResponseBuilder

AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs
VIH-7007 
VIH-7157 
VIH-7199 
Only send amendment email if date or time has changed
```
[ ] Yes
[x] No
```
=> VIH-7007 Only send amendment email if date or time has changed

AdminWebsite/AdminWebsite.AcceptanceTests/Pages/EditParticipantNamePage.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/edit-participant/edit-participant-search-results/edit-participant-search-results.component.ts
VIH-6637
Update error message when a user with a contact email is not found
```
[ ] Yes
[x] No
```
=> VIH-6637 Update error message

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs
VIH-7007
fix incorrect condition
```
[ ] Yes
[x] No
```
=> VIH-7007 fix incorrect condition

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs, AdminWebsite/AdminWebsite.UnitTests/Extensions/ConferenceDetailsResponseExtensionsTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingReminderNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Extensions/ConferenceDetailsResponseExtensions.cs, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs, AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
VIH-6373
VIH-6379
VIH-7006
VIH-6373 Send a reminder email to JOHs when hearing is confirmed
VIH-6379 Send a reminder email to individuals when hearing is confirmed
VIH-7006 Send a reminder email to representatives when hearing is confirmed
```
[ ] Yes
[x] No
```
=> VIH-6373 Send reminder email when hearing is confirmed

AdminWebsite/AdminWebsite.AcceptanceTests/Data/DateFormats.cs
https://tools.hmcts.net/jira/browse/VIH-5552
- workaround for Rider Current Culture in test execution
```
[ ] Yes
[X] No
```
=> VIH-5552 Rider Current Culture Workaround

AdminWebsite/AdminWebsite.TestAPI.Client/TestApiClient.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Startup.cs, AdminWebsite/AdminWebsite/appsettings.Development.json, AdminWebsite/AdminWebsite/appsettings.json
VIH-7341
enable app insights logging
```
[ ] Yes
[x] No
```
=> VIH-7341 enable app insights logging

AdminWebsite/AdminWebsite.AcceptanceTests/Features/AddParticipants.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs
https://tools.hmcts.net/jira/browse/VIH-6895
-Updated linkedparticipant scenario
```
[ ] Yes
[x] No
```
=> VIH-6895 Updated linkedparticipant edit scenario

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
https://tools.hmcts.net/jira/browse/VIH-6896
- Update interpreter AC
```
[ ] Yes
[x] No
```
=> VIH-6896 Updated interpreter assertion

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.ts
VIH-7323
* filter out wingers to prevent duplication in array
```
[ ] Yes
[x] No
```
=> VIH-7323 prevent duplicate winger items

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-participant-list/booking-participant-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-participant-list/booking-participant-list.component.ts
VIH-7323
* sort participants in booking details view
* group interpreter & interpretee
* improve test set-up
```
[ ] Yes
[x] No
```
=> VIH-7323 sort participants & group interpreters

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, azure-pipelines.beta.yml, azure-pipelines.release.yml, azure-pipelines.yml
- Smoke tests skipped
```
[ ] Yes
[X] No
```
=> VIH-5552 smoke tests skipped

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Data/TestData/DefaultData.xml, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/pipe-stringifier.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/pipe-stringifier.service.ts
https://tools.hmcts.net/jira/browse/VIH-7472
removed null text entry
```
[ ] Yes
[X] No
```
=> VIH-7472 removed null text entry

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts
https://tools.hmcts.net/jira/browse/VIH-7507
- fix to update the participant list on remove interpreter/interpreted for
```
[ ] Yes
[x] No
```
=> VIH-7507 remove participant scenario issue

AdminWebsite/AdminWebsite.UnitTests/Extensions/HearingDetailsResponseExtensionsTests.cs, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs
https://tools.hmcts.net/jira/browse/VIH-7484
- added fix to email judge on personal email when hearing is confirmed.
```
[ ] Yes
[x] No
```
=> VIH-7484 when a hearing is confirmed it is getting sent out to judge hmcts account

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
- upgrade to latest AC package
```
[ ] Yes
[X] No
```
=> VIH-5552 upgrade AC package

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
- removing unnecessary step causing tests to fail
```
[ ] Yes
[X] No
```
=> VIH-5552 Removing unnecessary step causing test failures

AdminWebsite/AdminWebsite/Services/HearingsService.cs
VIH-7502
Judge no longer received amendment emails before confirm for multi day hearings
```
[ ] Yes
[x] No
```
=> VIH-7502 judge sent amendment email mdh

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingDetails.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/EditParticipantName.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingConfirmationSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingsListSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/EditParticipantNameSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/GetAudioFileSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
- Upgraded package
```
[ ] Yes
[X] No
```
=> VIH-5552 Update GetText

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
- update to ClickBook() to prevent stale reference
```
[ ] Yes
[X] No
```
=> VIH-5552 Test fix

AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/delete-participant/delete-participant-search-results/delete-participant-search-results.component.ts
VIH-7500
* wording updates
* couple of ts improvements
```
[ ] Yes
[x] No
```
=> VIH-7500 update delete user wording

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
VIH-7515
only send judge notice email when an email address has been updated AND hearing is confirmed
```
[ ] Yes
[x] No
```
=> VIH-7515 send judge notification only for confirmed hearings

AdminWebsite/AdminWebsite/ClientApp/src/app/app-routing.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/app.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts
https://tools.hmcts.net/jira/browse/VIH-7573
- Fix edit hearing details bug
```
[ ] Yes
[X] No
```
=> VIH-7573 Fix edit hearing details bug

AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts
VIH-7616
* include 'type' property in linked participant mapping
* use a reduce instead of a foreach
```
[ ] Yes
[x] No
```
=> VIH-7616 map linked participant type

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Extensions/HearingDetailsResponseExtensionsTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingAmendmentNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToMultiDayHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/package.json, AdminWebsite/AdminWebsite/Contracts/Requests/BookHearingRequest.cs, AdminWebsite/AdminWebsite/Controllers/JudiciaryAccountsController.cs, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs, AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-7374
VIH-7540
* send ejud emails:
* hearing confirmation
* hearing confirmation MDH
* hearing amendment
```
[ ] Yes
[x] No
```
=> VIH-7374 judge ejud emails

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertHearing.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/DateHelper.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/TestContext.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/HearingScheduleSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/security/auth-config.module.ts, AdminWebsite/AdminWebsite/Startup.cs
VIH-7419
update config for OIDC and ShowPII
```
[ ] Yes
[x] No
```
=> VIH-7419 update config for OIDC and ShowPII

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts
VIH-7627
* use getRawValue() instead of value to get the values of hearing type and case type
```
[ ] Yes
[x] No
```
=> VIH-7627 get hearing type from disabled field

AdminWebsite/AdminWebsite/ClientApp/src/app/get-audio-file/hearing-search-results/hearing-search-results.component.html, AdminWebsite/AdminWebsite/ClientApp/src/styles.scss
VIH-7424
* add a word break for case number only
```
[ ] Yes
[x] No
```
=> VIH-7424 add word break for case number

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingAmendmentNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingReminderNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToMultiDayHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs, AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-7373
- Updated NotificationApi.Client NuGet
- Updated the mapper to Send notification to EJud JOH on the hearing confirmation both single and multi day
```
[ ] Yes
[x] No
```
=> VIH-7373  Added Hearing confirmnation for ejud joh single and multi day

AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/other-information-model.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/other-information.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/pipe-stringifier.service.ts
VIH-7629
Only send other information details to API if they are present. Without this change the requests work for the latest in master but on dev return a 403, see ticket for details.
```
[ ] Yes
[x] No
```
=> VIH-7629 Other Information Changes

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Validators/EditHearingRequestValidatorTest.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Validators/EditHearingRequestValidator.cs
VIH-7621
The hearing scheduled time was being reset to the end of the day
30 minutes were being subtracted to the current time rather than added
```
[ ] Yes
[x] No
```
=> VIH-7621 Making a user unable to edit a confirmed hearing under 30 minutes

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html
VIH-7637
* update style to accommodate the max width of results
* affects judge and participant search
```
[ ] Yes
[x] No
```
=> VIH-7637 increase search input box width

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-7668
https://tools.hmcts.net/jira/browse/VIH-7673
https://tools.hmcts.net/jira/browse/VIH-7674
- Able to add panel member to a hearing.
- Update the panel member details
- Retrieving all the details of a panel member
for confirmed and unconfirmed hearings
```
[ ] Yes
[x] No
```
=> VIH-7668 VHO can edit, add panel member to confirmed/unconfirmed

AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.ts
VIH-7701
REmoves eJud accounts from search and re-allows us to check for aad
```
[ ] Yes
[x ] No
```
=> VIH-7701 Commented out eJud searching & relpaced with aad accounts

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
VIH-7728 
Get rid of the code for adding ejud panel member into a hearing
```
[ ] Yes
[x ] No
```
=> VIH-7728 Revert part of changes in VIH7668

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts
VIH-7734
* add public holiday validator
```
[ ] Yes
[x] No
```
=> VIH-7734 add public holiday validation

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/item/participant-item.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/item/participant-item.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/item/participant-item.component.ts
VIH-7753
Removing change button for a judge when editing a hearing inside 30 minutes
```
[ ] Yes
[ x] No
```
=> VIH-7753 Change (judge) button shouldn't be displayed during last minute booking

charts/vh-admin-web/Chart.yaml
Chart version bump
```
[ ] Yes
[ ] No
```
=> VIH-0000 Update Chart.yaml

AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToDemoOrTestNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-7335
- send notifications to judge or ejud judge 
```
[ ] Yes
[x] No
```
=> VIH-7335 Sending Notification Email for judge and ejud judge

azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7660
```
[ ] Yes
[X] No
```
=> VIH-7660 changed PAT

charts/vh-admin-web/values.yaml
N/A
Bumped image version
```
[ ] Yes
[X] No
```
=> VIH-7545 - Version bump

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingDetailsSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingsListSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7738
```
[ ] Yes
[x] No
```
=> VIH-7738 Some logging for better understanding

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json
https://github.com/hmcts/vh-video-web/pull/1438/commits
Updates to only the dependent nuget apis on test projects
```
[ ] Yes
[ ] No
```
=> VIH-7783 api nuget updates for test projects only

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/VideoAccessPointsSteps.cs
wait until edit element is found
https://tools.hmcts.net/jira/browse/VIH-7819
Wait time logic added for the element to appear.
```
[ ] Yes
[x] No
```
=> VIH-7819 fix for edit video endpoint script

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs, AdminWebsite/AdminWebsite.UnitTests/stryker-config.json, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/confirm-booking-failed-popup/confirm-booking-failed-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/confirm-booking-failed-popup/confirm-booking-failed-popup.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/confirm-booking-failed-popup/confirm-booking-failed-popup.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/wait-popup/wait-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/wait-popup/wait-popup.component.spec.ts, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-7760 
- changed AdminApi - UpdateBookingStatus method in Hearing API to handle excetions (normal, video, booking) for creation/cancellation actions.
- changed text in popup frames as per story/wire frame in sotry VIH-7560 
```
[ ] Yes
[ x] No
```
=> VIH-7760 - changes done to fix retry of failed confirmation booking

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/LoginSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
https://github.com/hmcts/vh-acceptance-tests/pull/50
Change is to use the SignOut property which has the correct title value
```
[ ] Yes
[x] No
```
=> VIH-7888 apply the correct sign out title value

AdminWebsite/AdminWebsite/Services/HearingsService.cs
- fix the Notify issue during the booking
https://tools.hmcts.net/jira/browse/VIH-7834
-  
```
[ ] Yes
[x] No
```
=> VIH-7834 revert changes

AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingAmendmentNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingReminderNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToMultiDayHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
https://tools.hmcts.net/jira/browse/VIH-7896
- Unhiding the removed code for Release 1.26
```
[ ] Yes
[x] No
```
=> VIH-7896 Unhide ejud for the notification types

AdminWebsite/AdminWebsite/Services/ConferenceDetailsService.cs
https://tools.hmcts.net/jira/browse/VIH-7760
```
[ ] Yes
[ x] No
```
=> VIH-7760 futher adjusting the timing for retries duration changed

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts
https://tools.hmcts.net/jira/browse/VIH-7910
```
[ ] Yes
[x ] No
```
=> VIH-7910 changes made to fix user name instead of email 

azure-pipelines.release.yml
https://tools.hmcts.net/jira/browse/VIH-6831
Passes a new var to the release template VanityUrl which contains the upper env url
```
[ ] Yes
[X] No
```
=> VIH-6831 automate vanity urls

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant-details.model.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/participant.model.ts
https://tools.hmcts.net/jira/browse/VIH-7867
```
[ ] Yes
[x ] No
```
=> VIH-7867 Fixed edit booking judge email field display

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-7927
- update the user name same as the contact email.
```
[ ] Yes
[x] No
```
=> VIH-7927 - Assigning Username same as contact email

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/wait-popup/wait-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/wait-popup/wait-popup.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/popups/wait-popup/wait-popup.component.ts
https://tools.hmcts.net/jira/browse/VIH-7931 
```
[ ] Yes
[x ] No
```
=> VIH-7931 Changes to popup text when doing booking or confirming a booking

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7974
Removal of duplicate code line
```
[ ] Yes
[x] No
```
=> VIH-7974 - remove duplicate entry of email address for 'Assign Judge With Email and Phone' script

AdminWebsite/AdminWebsite/ClientApp/src/app/services/error.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/error.service.ts
https://tools.hmcts.net/jira/browse/VIH-7821
updated error service to return unauthorised error page when the http status code returned is 403 (forbidden) 
```
[ ] Yes
[x] No
```
=> VIH-7821 updated error service to display unauthorised page for 403

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html
https://tools.hmcts.net/jira/browse/VIH-7807
```
[ ] Yes
[ x] No
```
=> VIH-7807 Assign Judge page accessibility fix

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-7830
added logic to handle case where linked participant email is null
```
[ ] Yes
[x] No
```
=> VIH-7830 added logic to handle case where linked participant email is null

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-7830
- updated the logic to query for a linked participant before creating the update request for bookings api
```
[ ] Yes
[x] No
```
=> VIH-7830 fix: unable to edit interpreter

AdminWebsite/AdminWebsite.AcceptanceTests/Features/GetAudioFile.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Helpers/TestContext.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/GetAudioFileSteps.cs
New script to check for separate audio recordings for a main hearing room (with interpreter VMR)
https://tools.hmcts.net/jira/browse/VIH-7984
New script
```
[ ] Yes
[x] No
```
=> VIH-7984 separate audio recordings for main hearing room with interpreter

AdminWebsite/AdminWebsite.UnitTests/Controllers/ReferenceDataControllerTests.cs, AdminWebsite/AdminWebsite/Controllers/ReferenceDataController.cs
https://tools.hmcts.net/jira/browse/VIH-7949
```
[ ] Yes
[X] No
```
=> VIH-7949 remove AAD group dependency for hearing types filtering

AdminWebsite/AdminWebsite.AcceptanceTests/Features/Errors.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Features/GetAudioFile.feature
Removal of 'Unsupported browser' test
https://tools.hmcts.net/jira/browse/VIH-8004
Removal of 'Unsupported browser' test since the browsers are now supported.
```
[ ] Yes
[x] No
```
=> VIH-8004 - Remove tests in Admin web for unsupported browsers

AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7723
logging the number of questions and answers to a questionnaire
```
[ ] Yes
[x] No
```
=> VIH-7723 add logging to questionnaire

AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
https://tools.hmcts.net/jira/browse/VIH-8039
- Able to add PM when the case type is generic
```
[ ] Yes
[x] No
```
=> VIH-8039 Able to add PM when the case type is generic

AdminWebsite/AdminWebsite.UnitTests/Controllers/PersonsControllerTest.cs, AdminWebsite/AdminWebsite/Controllers/PersonsController.cs
https://tools.hmcts.net/jira/browse/VIH-7978
```
[ ] Yes
[x ] No
```
=> VIH-7978 - Refactor participant search and remove search exclusion logic not required anymore from AAD and Edjudge

AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-8066
- Was using Case type name instead of the hearing name now it is fixed.
```
[ ] Yes
[x] No
```
=> VIH-8066 Casetype instead hearing type

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-8061
```
[ ] Yes
[x] No
```
=> VIH-8601 - Booking failure when a existing particpant without AAD account is added to hearing.

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/AddNotificationRequestMapperTest.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToDemoOrTestNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingAmendmentNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToMultiDayHearingConfirmationNotificationTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-7798
https://tools.hmcts.net/jira/browse/VIH-7797
https://tools.hmcts.net/jira/browse/VIH-7799
https://tools.hmcts.net/jira/browse/VIH-8069
- Added below notification types for the participants in the hearing
CreateStaffMember 
HearingAmendmentStaffMember 
HearingConfirmationStaffMember 
HearingConfirmationStaffMemberMultiDay 
StaffMemberDemoOrTest 
```
[ ] Yes
[x] No
```
=> VIH-7798 Staff Member notification mappings

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/copy-join-link/copy-join-link.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/copy-join-link/copy-join-link.component.ts
https://tools.hmcts.net/jira/browse/VIH-8098
- updated the url for the quick join
```
[ ] Yes
[x] No
```
=> VIH-8098 added url for quick join link

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/DataHooks.cs
=> VIH-8108 - Added debugging

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
Update to latest packages
```
[ ] Yes
[ ] No
```
=> VIH-8030 - Update packages

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8036
Update videoApi.Client to include StaffMember in the booking confirmation logic
```
[ ] Yes
[X] No
```
=> VIH-8036 VHO confirms booking with Staff Member

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/Controllers/StaffMemberControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.ts, AdminWebsite/AdminWebsite/Controllers/StaffMemberController.cs, AdminWebsite/AdminWebsite/packages.lock.json, README.md
https://tools.hmcts.net/jira/browse/VIH-8034
- Ability to search for the staff member
```
[ ] Yes
[x] No
```
=> VIH-8034 add existing staff member to the hearing

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-7797
- Extract notifications for new and edit hearings
```
[ ] Yes
[x] No
```
=> VIH-7797 Extract new and edit hearing confirmation notifications

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts
https://tools.hmcts.net/jira/browse/VIH-8148
=> VIH-8148 Fixed bugs when adding & editing staff member

AdminWebsite/AdminWebsite.AcceptanceTests/Pages/AssignJudgePage.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-staff-member/add-staff-member.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-staff-member/add-staff-member.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
https://tools.hmcts.net/jira/browse/VIH-8175
- Upon adding staff member search field it needed a unique id to support automation tests
```
[ ] Yes
[x] No
```
=> VIH-8175 added different locators for judge and staff member

AdminWebsite/AdminWebsite.AcceptanceTests/Data/TestData/DefaultData.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingConfirmation.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/AssignJudgePage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AssignJudgeSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/ProgressionSteps.cs
https://tools.hmcts.net/jira/browse/VIH-8175
```
[ ] Yes
[ ] No
```
=> VIH-8175 - initial script to add new staff member

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/search.service.ts, AdminWebsite/AdminWebsite/Contracts/Enums/RoleNames.cs, AdminWebsite/AdminWebsite/Controllers/FeatureFlagController.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-8215
when EJUD Feature Flag is OFF
- VHO will not be able to select eJudiciary accounts for judge role
- VHO will not be able to select eJudiciary accounts for panel member/winger role
- VHO will be able to create AAD panel member/winger accounts. 
when EJUD Feature Flag is ON
- VHO will be able to select eJudiciary accounts for judge role
- VHO will be able to select eJudiciary accounts for panel member/winger role
- VHO will not be able to create AAD panel member/winger accounts. 
```
[x] Yes
[ ] No
```
=> VIH-8215 Ejud feature flag enabled/disabled

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/other-information/other-information.component.spec.ts
https://tools.hmcts.net/jira/browse/VIH-7871
=> VIH-8251 staff member breadcrumb feature toggle

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Configuration/AdminWebConfig.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/HearingSchedulePage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/appsettings.json, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-7954
```
[ ] Yes
[ ] No
```
=> VIH-7954 some script fixes

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8337
- updated video api client 
- fixed serilization issue in tear down step
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> VIH-8337 updated video api version

AdminWebsite/AdminWebsite.AcceptanceTests/Features/QuickLinks.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Pages/SummaryPage.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/AddParticipantSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BookingConfirmationSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/BrowserSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/OtherInformationSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs
https://tools.hmcts.net/jira/browse/VIH-8400
New Quick Link scripts for booking a hearing without participants
```
[ ] Yes
[ ] No
```
=> VIH-8400 booking a hearing with no participants

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8030
```
[ ] Yes
[ ] No
```
=> VIH-8030 update to latest acceptance test proj

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts
merging the latest changes from master to release branch
tickets:
VIH-8030
VIH-8440
=> VIH-8030 VIH-8440 Merge latest to release 1.29

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumbItems.ts
VIH-8518
Remove "staff" from breadcrumb
```
[ ] Yes
[x] No
```
=> VIH-8518 Remove "staff" from breadcrumb

AdminWebsite/AdminWebsite.UnitTests/Extensions/HearingDetailsResponseExtensionsTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs
https://tools.hmcts.net/jira/browse/VIH-8545
When editing a generic hearing, the correct test demo email will be sent to judge's
```
[ ] Yes
[x] No
```
=> VIH-8545 send correct email for test demo on edit judge

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/QuestionnaireSteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/SummarySteps.cs, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8538
```
[ ] Yes
[ ] No
```
=> VIH-8538 Testing changes done to acceptance criteria solution

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts, AdminWebsite/AdminWebsite/Contracts/Responses/ClientSettingsResponse.cs, azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8435
=> VIH-8435 Added support for copying Welsh telephone number

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, azure-pipelines.yml
=> VIH-7990 - Update Dependencies due to ChromeDriver update.

AdminWebsite/AdminWebsite.AcceptanceTests/Data/AssertConference.cs, AdminWebsite/AdminWebsite.AcceptanceTests/Features/BookingConfirmation.feature, AdminWebsite/AdminWebsite.AcceptanceTests/Steps/ProgressionSteps.cs
https://tools.hmcts.net/jira/browse/VIH-7954
1) trim() function applied to some variables as some scripts were failing to extra spaces.
2) Removal of a staff member script and function
```
[ ] Yes
[x] No
```
=> VIH-7954 - trim() applied and removal of a staff member script

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
update of bookings API
VIH-7954
```
[ ] Yes
[ ] No
```
=> VIH-7954 update of bookings API nuget package

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-8629
- Should not send the remainder emails up on confirmation
```
[ ] Yes
[x] No
```
=> VIH-8629 Should not send the remainder emails up on confirmation

AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-8629
- optional contact email for judge
```
[ ] Yes
[x] No
```
=> VIH-8629 judge email optional for notification

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json
VIH-7954
Update to latest nuget versions
```
[ ] Yes
[ ] No
```
=> VIH-7954 Update to latest dependency versions

azure-pipelines.beta.yml, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
N/A
Add the FeatureToggle launchdarkly key into more places in the various pipelines.
```
[ ] Yes
[x] No
```
=> VIH-8816 Add feature toggle into more pipelines

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/packages.lock.json
[VIH-8568](https://tools.hmcts.net/jira/browse/VIH-8568)
- updated bookings api package reference
```
[ ] Yes
[x] No
```
=> VIH-8568 updated bookings api package reference

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/Controllers/BookingListControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Controllers/BookingListController.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8797
Adds the backend/API changes for searching bookings by venues.
```
[ ] Yes
[x] No
```
=> VIH-8797 Add functionality to search bookings by venues (backend changes)

AdminWebsite/AdminWebsite.UnitTests/Controllers/BookingListControllerTest.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/Controllers/BookingListController.cs
https://tools.hmcts.net/jira/browse/VIH-8796
Added functionality to search and filter bookings list by case type. 
```
[ ] Yes
[x ] No
```
=> VIH-8796 filter bookings by case type

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/Controllers/BookingListControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/Controllers/BookingListController.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8743
Adds start and end date search functionality to the booking list.
```
[ ] Yes
[x] No
```
=> VIH-8743 Add functionality to search bookings by start and end date

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts
https://tools.hmcts.net/jira/browse/VIH-8743
Fixes issues with the date search on the booking list.
- Prevent searching on historical dates
- Fixes an issue where the date range validation can be bypassed by typing in the dates. As part of the onBlur event, clear the input if it is invalid
```
[ ] Yes
[x] No
```
=> VIH-8743 Fix issues with date search

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts
[VIH-8796](https://tools.hmcts.net/jira/browse/VIH-8796)
```
[ ] Yes
[x ] No
```
=> VIH-8796 Added sort to the caseTypes list

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/Controllers/BookingListControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-list.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/Contracts/Requests/BookingSearchRequest.cs, AdminWebsite/AdminWebsite/Controllers/BookingListController.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8730
- Added bookings list search by participant's last name
```
[x] Yes
[ ] No
```
=> VIH-8730 Bookings list search by participant's last name

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/CancelHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/UpdateBookingStatusTests.cs, AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/package.json, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-8833
Implemented booking without a judge functionality: See commits for details.
```
[ ] Yes
[x] No
```
=> VIH-8833 vho can book hearing with no judge

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking-routing.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumbItems.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/security/last-minute-amendments.guard.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/security/last-minute-amendments.guard.ts, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-8820
Allows the judge to be edited for a booking within the 30 minute window of the hearing starting.
```
[ ] Yes
[x] No
```
=> VIH-8820 Allow judge to be changed last minute

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/JudiciaryAccountsControllerTest.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/UserResponseMapperTest.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant-base/add-participant-base.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Controllers/JudiciaryAccountsController.cs, AdminWebsite/AdminWebsite/Mappers/UserResponseMapper.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8980
=> VIH-8980 Retrieve judges with joh group if not found in db

AdminWebsite/AdminWebsite.AcceptanceTests/Hooks/ConfigHooks.cs, AdminWebsite/AdminWebsite/Configuration/FeatureToggles.cs, AdminWebsite/AdminWebsite/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-9167
Changed launchDarkly logging level to Warn and above to reduce verbosity in pipeline logs
```
[ ] Yes
[X] No
```
=> VIH-9167 configure logging level for LaunchDarkly 

charts/vh-admin-web/Chart.yaml, charts/vh-admin-web/values.yaml
VIH-9236
Add Username Stem secret
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add Username Stem

azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, variables/shared.yaml
VIH-9254
Add AAD Redirect URL on PR open
Remove AAD Redirect URLs on PR close
```
[ ] Yes
[ x ] No
```
=> VIH-9254 - Add and Remove AAD Redirect URLs

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
HearingsController.cs cleanup, removed unused dependencies and split …
=> VIH-9230 Hearings Controller cleanup and refactor

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-9310
```
[ ] Yes
[X] No
```
=> VIH-9310 Fixed username being set to contact email for new user

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/AdminWebsite.IntegrationTests.csproj, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/Controllers/ReferenceDataControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/UserIdentityControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/user-identity.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/user-identity.service.ts, AdminWebsite/AdminWebsite/Contracts/Responses/UserProfileResponse.cs, AdminWebsite/AdminWebsite/Controllers/ReferenceDataController.cs, AdminWebsite/AdminWebsite/Controllers/UserIdentityController.cs, AdminWebsite/AdminWebsite/Helper/AdministratorRoleClaims.cs, AdminWebsite/AdminWebsite/Helper/ClaimNames.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9291
=> VIH-9291 Save VH team lead status to User profile

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.html
https://tools.hmcts.net/jira/browse/VIH-9286
```
[ ] Yes
[X] No
```
=> VIH-9286 Changed html label for quicklinks

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/appsettings.json, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/AdminWebsite.IntegrationTests.csproj, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.Testing.Common/AdminWebsite.Testing.Common.csproj, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Dockerfile, AdminWebsite/AdminWebsite/packages.lock.json, azure-pipelines.release.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-9202
Upgraded target framework to .NET6
```
[ ] Yes
[X] No
```
=> VIH-9202 Upgraded Target Framework to dotnet 6 

AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts
https://tools.hmcts.net/jira/browse/VIH-9360
refactor to save welsh number in session storage
=> VIH-9360 - Telephone number is same as english number for Multi Day hearing

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts
https://tools.hmcts.net/jira/browse/VIH-9221
- Removes the tooltip from start and end time fields (min and max attributes)
- Fixes error after setting start or end time to an empty value
- Clear the confirmation messages after navigating away via search, edit or cancel
```
[ ] Yes
[x] No
```
=> VIH-9348 Fixes for edit non-availability hours

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts
https://tools.hmcts.net/jira/browse/VIH-9278
Added a date filter for the non availability work hours table
```
[ ] Yes
[X] No
```
=> VIH-9278 Added non-availability work hours date filter

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts
https://tools.hmcts.net/jira/browse/VIH-9278
Changed logic based on QA feedback, but fixed a U.I bug where buttons were appearing through popup
```
[ ] Yes
[X] No
```
=> VIH-9278 team leader filters non availability hours

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-non-work-hours-model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.scss
https://tools.hmcts.net/jira/browse/VIH-9462
Changed add date to also turn on edit mode. Also fixed an issue where you cant delete a slot that has just been generated; opens the prompt so that it can send a delete request to the server (does not need to send request to server as it is not created in the db yet) - so will just remove it without the prompt in this case.
```
[] Yes
[X] No
```
=> VIH-9462 turn on edit mode when add non availability hours is selected

AdminWebsite/AdminWebsite/Dockerfile
https://tools.hmcts.net/jira/browse/VIH-9477
Add curl to the docker build
```
[ ] Yes
[ X] No
```
=> VIH-9477 Add-curl-to-docker-build

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-search/vho-search.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-search/vho-search.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts
https://tools.hmcts.net/jira/browse/VIH-9431
=> VIH-9431 Show non availability table when empty

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts
Added the message showing 20 records only to user ;
https://tools.hmcts.net/jira/browse/VIH-9447
```
[ ] Yes
[ x] No
```
=> VIH-9447 ShowOnlyTwentyRecordsFix

AdminWebsite/AdminWebsite/ClientApp/src/app/services/config.service.ts
https://tools.hmcts.net/jira/browse/VIH-9486
added no cache headers
=> VIH-9486 - added no cache headers

AdminWebsite/AdminWebsite/ClientApp/src/app/app-routing.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/guards/change.guard.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/guards/changes.guard.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-search/vho-search.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-search/vho-search.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-search/vho-search.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-table/vho-work-hours-table.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.ts
https://tools.hmcts.net/jira/browse/VIH-9344
handle leaving page while editing
=> VIH-9344 - vho edits working hours and non availability hours

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9517 - add master release pipeline
VIH-9517 - add master release pipeline
```
[ ] Yes
[x ] No
```
=> VIH-9517 - add master release pipeline

azure-pipelines.sds.pr-release.yml
VIH-9532 - Amend PR Pipeline
VIH-9532 - Amend PR Pipeline
```
[ ] Yes
[ x ] No
```
=> VIH-9532 - Amend PR Pipeline

AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts
https://tools.hmcts.net/jira/browse/VIH-9493
added apostrophe to regex expression
=> VIH-9493 - added apostrophe to regex expression

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.html
https://tools.hmcts.net/jira/browse/VIH-9551
changed html ID
=> VIH-9551 - changed id

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.html
https://tools.hmcts.net/jira/browse/VIH-9565
Adds missing labels
```
[ ] Yes
[x] No
```
=> VIH-9565 Accessibility fixes for missing labels

charts/vh-admin-web/Chart.yaml, charts/vh-admin-web/values.dev.template.yaml
upgrade java chart to 4.0.6
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - upgrade java chart to 4.0.6

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.ts
https://tools.hmcts.net/jira/browse/VIH-9582
Adds frontend check to prevent uploading multiple work hour rows for the same user
```
[ ] Yes
[x] No
```
=> VIH-9582 Add frontend validation for uploading work hours with duplicate users

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.component.spec.ts
https://tools.hmcts.net/jira/browse/VIH-9452
Changed error message
=> VIH-9452 - Changed error message

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts
VIH-9454
stop showing message when non work hour row is deleted since parent component shows it
```
[ ] Yes
[x] No
```
=> VIH-9454 remove duplicate success message

AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.ts
https://tools.hmcts.net/jira/browse/VIH-9503
```
[ ] Yes
[ x] No
```
=> VIH-9503 Disable cso access to work allocation 

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts, AdminWebsite/AdminWebsite/Mappers/UnallocatedHearingsForVHOMapper.cs
https://tools.hmcts.net/jira/browse/VIH-9693
See commit
```
[ ] Yes
[X] No
```
=> VIH-9693 fix for bug found in prod release 1 42

charts/vh-admin-web/Chart.yaml, charts/vh-admin-web/values.yaml
Updated chart to get launch darkly client id from infra keyvalut rather than app one
=> VIH-9401 launch darkly keyvault change

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts
VIH-9463
* move validation functionality from onBlur to button click
* in edit mode, disable save button until changes are made
* fix resulting broken tests
* apply standard form styling
* refac validation logic
```
[ ] Yes
[X] No
```
=> VIH-9463 allocation table validation 2

AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.ts
VIH-9306
- display add button even with fuzzy search
- replace edit and delete justice user button with icons
- replace contact email on table with contact telephone
```
[ ] Yes
[x] No
```
=> VIH-9306 display add button even with fuzzy search

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/JusticeUserController/DeleteJusticeUserTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/pop-ups/confirm-delete-justice-user-popup/confirm-delete-justice-user-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/pop-ups/confirm-delete-justice-user-popup/confirm-delete-justice-user-popup.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/pop-ups/confirm-delete-justice-user-popup/confirm-delete-justice-user-popup.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/styles.css, AdminWebsite/AdminWebsite/Controllers/JusticeUsersController.cs, AdminWebsite/AdminWebsite/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9367
Adds frontend functionality for deleting a justice user
```
[ ] Yes
[x] No
```
=> VIH-9367 Delete justice user

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/JusticeUserController/AddNewJusticeUserTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/JusticeUserController/EditJusticeUserTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/justice-user-form/justice-user-form.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/justice-user-form/justice-user-form.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/justice-user-form/justice-user-form.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.ts, AdminWebsite/AdminWebsite/Controllers/JusticeUsersController.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-9352
* use existing 'add user' dialog to allow user to edit a user's role
* disable all form fields apart from Role
* add new EditJusticeUser endpoint
```
[ ] Yes
[x] No
```
=> VIH-9352 add edit justice user feature

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/allocate-hearings/models/allocate-hearing.model.ts
VIH-9630
* resets the counter for fewer than 2 concurrent hearings
```
[ ] Yes
[x] No
```
=> VIH-9630 reset concurrent count

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/justice-user-form/justice-user-form.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.html
VIH-9352
* update cancel button to 'discard changes'
* update 'team lead' to 'administrator'
```
[ ] Yes
[x] No
```
=> VIH-9352 update button & role labels

AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/services/work-hours-file-processor.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/services/work-hours-file-processor.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.ts
https://tools.hmcts.net/jira/browse/VIH-9772
- added duplicate user check
- added error message
=> VIH-9772 - added duplicate user check

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/JusticeUserController/RestoreJusticeUserTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/UserIdentityControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/manage-team/manage-team.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/pop-ups/confirm-restore-justice-user-popup/confirm-restore-justice-user-popup.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/pop-ups/confirm-restore-justice-user-popup/confirm-restore-justice-user-popup.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/pop-ups/confirm-restore-justice-user-popup/confirm-restore-justice-user-popup.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/work-allocation.module.ts, AdminWebsite/AdminWebsite/Controllers/JusticeUsersController.cs, AdminWebsite/AdminWebsite/Controllers/UserIdentityController.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-9744
* includes deleted users in search results
* indicates deleted users with badge
* allows restore of deleted users & confirmation dialog
* hides delete & edit icons
```
[ ] Yes
[x] No
```
=> VIH-9744 show deleted users & allow restore

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/services/work-hours-file-processor.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/services/work-hours-file-processor.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/upload-work-hours/upload-work-hours.component.ts
https://tools.hmcts.net/jira/browse/VIH-9771
added check for the right file exception
=> VIH-9771 - Work Allocation CSV file upload expects not to accept wrong file format

AdminWebsite/AdminWebsite/ClientApp/src/styles.css
https://tools.hmcts.net/jira/browse/VIH-9839
increased z-index for modal popup window
=> VIH-9839 - Update css for overlay popup

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/assign-judge/assign-judge.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/formatters/remove-special-characters.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/formatters/sanitize-input-text.ts
https://tools.hmcts.net/jira/browse/VIH-8866
Validation added against special characters
=> VIH-8866 - Special Characters Validation on Hearing Details Form

AdminWebsite/AdminWebsite/ClientApp/src/app/shared/menus/justice-users-menu/justice-users-menu.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/menus/justice-users-menu/justice-users-menu.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/menus/justice-users-menu/justice-users-menu.component.ts
https://tools.hmcts.net/jira/browse/VIH-9876
Fixes an error when filtering the booking list by allocated CSO
```
[ ] Yes
[x] No
```
=> VIH-9876 Fix error filtering booking list by allocated cso

AdminWebsite/AdminWebsite.UnitTests/Mappers/UnallocatedHearingsForVHOMapperTests.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/unallocated-hearings/unallocated-hearings.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/unallocated-hearings/unallocated-hearings.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/unallocated-hearings/unallocated-hearings.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/Contracts/Responses/UnallocatedHearingsForVHOResponse.cs, AdminWebsite/AdminWebsite/Mappers/UnallocatedHearingsForVHOMapper.cs
https://tools.hmcts.net/jira/browse/VIH-9887
- Change wording on dashboard: This Week -> Next 7 Days
- Change wording on dashboard: This Month -> Next 30 Days
- Change Next 7 Days to query over next 7 days
- Change Next 30 Days to query over next 30 days
- Update property and method names for clarity
```
[ ] Yes
[x] No
```
=> VIH-9887 Change hearings dashboard to next 7 days and 30 days

AdminWebsite/AdminWebsite.AcceptanceTests/AdminWebsite.AcceptanceTests.csproj, AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/Middleware/UserClaimsMiddlewareTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Middleware/UserClaimsMiddleware.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-7741
Use the bearer token for the claims cache id to ensure latest claims are built each login
```
[ ] Yes
[x] No
```
=> VIH-7741 update cache claims key to bearer token

AdminWebsite/AdminWebsite.IntegrationTests/appsettings.json, AdminWebsite/AdminWebsite.UnitTests/AdminWebsite.UnitTests.csproj, AdminWebsite/AdminWebsite.UnitTests/appsettings.json, AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/package.json, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/bookings-list/bookings-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/security/refresh-token-parameter.interceptor.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/audio-link-service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/config.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-delete-service.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-delete-service.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/participant-edit-service.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/suitability/services/questionnaire-api.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/services/edit-work-hours.service.ts
updated all uses of deprecated toPromise to lastvaluefrom as recommended by rxjs docs
=> VIH-9918 fix for toPromise codesmell 

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Security/AuthenticationSchemes/VhAadSchemeTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/unallocated-hearings/unallocated-hearings.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/allocate-hearings/allocate-hearings.component.html, AdminWebsite/AdminWebsite/Controllers/ReferenceDataController.cs, AdminWebsite/AdminWebsite/Controllers/WorkAllocationController.cs, AdminWebsite/AdminWebsite/Security/Authentication/AadSchemeBase.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-9930
VIH-9936
*  assign claims to Principal claim in the context
* change auth policy for GET work allocation endpoints to standard policy
* update route for work allocation controller to avoid clashing with the hearings controller
```
[ ] Yes
[x] No
```
=> VIH-9936 Update auth policy

AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/package.json, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.ts
VIH-9944
do not show non work hours table if result is null
```
[ ] Yes
[x] No
```
=> VIH-9944 do not show non work hours table if result is null

AdminWebsite/AdminWebsite/Startup.cs
[VIH-9863](https://tools.hmcts.net/jira/browse/VIH-9863)
=> VIH-9863 - enable hsts

AdminWebsite/AdminWebsite/ClientApp/src/app/manage-team/justice-user-form/justice-user-form.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/manage-team/justice-user-form/justice-user-form.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/manage-team/manage-team/manage-team.component.ts
VIH-9951 
Clear Justice user form on discard or cancel
```
[ ] Yes
[x] No
```
=> VIH-9951 Clear Justice user form on discard or cancel

AdminWebsite/AdminWebsite/ClientApp/src/app/shared/select/select.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/allocate-hearings/allocate-hearings.component.html
https://tools.hmcts.net/jira/browse/VIH-9895
Fixed the issues where duplicate labels were causing the accessibility tests failures .
```
[ ] Yes
[x ] No
```
=> VIH-9895 axe results exceptions fix

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/edit-work-hours.component.ts
VIH-10039
filter non-available hours by end date
```
[ ] Yes
[x] No
```
=> VIH-10039 filter non-available hours by end date

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Contracts/Requests/BookingSearchRequest.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-10023
performance improvement for booking list
```
[ ] Yes
[x] No
```
=> VIH-10023 performance improvement for booking list

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs
As raised by cyber security , changed the domain name hmcs.net
https://tools.hmcts.net/jira/browse/VIH-7622
This ticket was raised by cyber security team that some areas in code base are exposing the name as security concern . Changed the domain name HMCTS.net to domain.net 
```
[ ] Yes
[x] No
```
=> VIH-7622 security repo issue on admin web

AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/services/work-hours-file-processor.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/services/work-hours-file-processor.service.ts, charts/vh-admin-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10060
Reports a validation error if the uploaded work hours csv contains too few or too many columns
```
[ ] Yes
[x] No
```
=> VIH-10060 Saturday Sunday validation missing for work hours

AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/endpoint.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking-details.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts, AdminWebsite/AdminWebsite/Services/HearingsService.cs
VIH-10068 
* link using the defence advocate contact email rather than ID
```
[ ] Yes
[x] No
```
=> VIH-10068 bug fix updating a hearing with linked video access endpoints

AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/package.json, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.ts
VIH-10069
init breadcrumb if current item has not been set by the time a user interacts
```
[] Yes
[x] No
```
=> VIH-10069 bug fix for breadcrumb when not initialised in a timely fashion

AdminWebsite/AdminWebsite.AcceptanceTests/packages.lock.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/WorkHoursControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/HearingUpdateRequestMapperTest.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/work-allocation/edit-work-hours/vho-work-hours-non-availability-table/vho-work-hours-non-availability-table.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/tslint.json, AdminWebsite/AdminWebsite/Controllers/WorkHoursController.cs, AdminWebsite/AdminWebsite/Mappers/HearingUpdateRequestMapper.cs, AdminWebsite/AdminWebsite/Models/LinkedParticipant.cs, AdminWebsite/AdminWebsite/packages.lock.json, charts/vh-admin-web/values.dev.template.yaml
VIH-10045
Update bookings api client to match changes
Fixed incorrect typing in contract classes
```
[ ] Yes
[] No
```
=> VIH-10045 Add missing domain methods for work allocation

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts
VIH-10105
Update regex to fail email validation when an ampersand is present
```
[ ] Yes
[x] No
```
=> VIH-10105 update regex for email validation

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant-base/add-participant-base.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
https://tools.hmcts.net/jira/browse/VIH-10133
Removed the redundant edit mode toggle from the add-participant component
```
[] Yes
[X] No
```
=> VIH-10133 Removed edit mode bool from update conditions

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts
VIH-10127
add endpoit display name client side validation
```
[ ] Yes
[x] No
```
=> VIH-10127 add endpoint display name client side validation

azure-pipelines.sds.pr-release.yml
Fixes an issue in the helm CI stage
=> VIH-0000 Fix for helm CI issue

AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/custom-validations/email-validator.spec.ts, charts/vh-admin-web/Chart.yaml
https://tools.hmcts.net/jira/browse/VIH-10005
PlatOps are reporting that there is over 3TB per month of logs generated by VH, need to reduce pod logging
=> VIH-10005 Reduce Logging

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/summary/summary.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/shared.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/truncatable-text/truncatable-text.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/styles.scss
VIH-7601
Handle long case name and number by applying 'Show More' with a tooltip
Add a truncatable text component to simplify this
When the max length has been exceeded, displays the correct message
------------
=> VIH-7601 Truncate long text

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/create-hearing/create-hearing.component.ts
VIH-10234
Hearing type is only required when ref data is off
=> VIH-10234 disable hearing type required when ref data toggle is on

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/PostHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/Configuration/FeatureToggles.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
VIH-10022
replace feature flag api call with launch darkly
=> VIH-10022 replace feature flag api call with launch darkly

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.html
VIH-10195
If the input is invalid, do not show the warning text 'No existing user account found - this will create a new one'
=> VIH-10195 only show warning that an account will be made if the input is valid

charts/vh-admin-web/Chart.yaml
=> VIH-10233 upping java chart

AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/manage-team/justice-user-form/justice-user-form.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/manage-team/justice-user-form/justice-user-form.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/justice-users.service.ts, AdminWebsite/AdminWebsite/packages.lock.json, charts/vh-admin-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10324
Removed disabling of properties
=> VIH-10324  allow users to edit justice user properties

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetStatusHearingTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Mappers/HearingDetailsResponseMapper.cs
Added Accounts created check before sending the success status to the client
=> VIH-10386 Added Accounts created check

AdminWebsite/AdminWebsite.UnitTests/Controllers/JudiciaryAccountsControllerTest.cs, AdminWebsite/AdminWebsite/Controllers/JudiciaryAccountsController.cs
https://tools.hmcts.net/jira/browse/VIH-10381
Have moved the code that searchs for ejudiciary acounts alongside regular accounts behind the Ejud Feature flag. If the flag is off will only search reform accounts. Only effects the V1 version of admin-web
=> VIH-10381 eJudiciary judge accounts are returned in prod (V1 API)

AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/BookNewHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Helper/HearingResponseV2Builder.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/add-judicial-office-holders/add-judicial-office-holders.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/add-judicial-office-holders/add-judicial-office-holders.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/add-judicial-office-holders/add-judicial-office-holders.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/models/add-judicial-member.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/search-for-judicial-member/search-for-judicial-member.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/search-for-judicial-member/search-for-judicial-member.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/search-for-judicial-member/search-for-judicial-member.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/bookings-persist.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts, AdminWebsite/AdminWebsite/Contracts/Requests/JudiciaryParticipantRequest.cs, AdminWebsite/AdminWebsite/Contracts/Responses/JudiciaryParticipantResponse.cs, AdminWebsite/AdminWebsite/Contracts/Responses/JudiciaryPerson.cs, AdminWebsite/AdminWebsite/Mappers/BookingDetailsRequestMapper.cs, AdminWebsite/AdminWebsite/Mappers/JudiciaryPersonResponseMapper.cs, AdminWebsite/AdminWebsite/packages.lock.json, charts/vh-admin-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10318
Added ability to add generic accounts via v2 forms, with optional contact email/telephone
=> VIH-10318 include generic hearing reform accounts in judiciary table

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/hearing-schedule/hearing-schedule.component.ts
[VIH-10457](https://tools.hmcts.net/jira/browse/VIH-10457)
initialised court name and court code
=> VIH-10457 INC5583659 Unable to book hearing when editing the date time before pressing book

AdminWebsite/AdminWebsite.UnitTests/Controllers/ReferenceDataControllerTests.cs, AdminWebsite/AdminWebsite/Controllers/ReferenceDataController.cs
https://tools.hmcts.net/jira/browse/VIH-10469
Updated the controller that returns the case types to also include case types without hearing types. Once the V2 feature toggle is turned on will likely need to revisit this with better design, once the hearing type entity is completely redundant.
=> VIH-10469 MRD casetypes not showing in dropdown

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetStatusHearingTests.cs, AdminWebsite/AdminWebsite/Configuration/FeatureToggles.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
https://tools.hmcts.net/jira/browse/VIH-10463
When multi-day bookings are created with the notify flag on, new users are created as part of the clone process instead of the first day/initial hearing creation, so don't wait for them to be created as part of the first day
=> VIH-10463 Fix for multi-day booking hearing creation failing with new users and notify flag on

AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditMultiDayHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/packages.lock.json, charts/vh-admin-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10336
- Pass the UpdatedBy property to the UpdateHearingsInGroup API endpoints, so that the last edited by is updated for enhanced multi-day edits
- Sonar fix
=> VIH-10336 Fix - last edited by not updated when changing participants

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Mappers/DefenceAdvocateMapperTests.cs, AdminWebsite/AdminWebsite/Mappers/DefenceAdvocateMapper.cs, AdminWebsite/AdminWebsite/Models/DefenceAdvocate.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs
https://tools.hmcts.net/jira/browse/VIH-10498
- Also use new participants when determining whether to update the endpoint
- Remove unused interface methods
=> VIH-10498 Fix - legal rep not linked to endpoint when editing the hearing

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/GetHearingTests.cs, AdminWebsite/AdminWebsite/Mappers/HearingDetailsResponseMapper.cs
https://tools.hmcts.net/jira/browse/VIH-10634
Fixes an error when loading the details page for a multi-day hearing whose days have all been cancelled or failed
=> VIH-10634 Fix error cancelling last active day of hearing

AdminWebsite/AdminWebsite.UnitTests/Security/AuthenticationSchemes/VhAadSchemeTests.cs, AdminWebsite/AdminWebsite/Security/Authentication/AadSchemeBase.cs
JsonWebToken
VIH-10707
update token validation to support when security token is a JsonWebToken
=> VIH-10707 update token validation to retrieve claims

AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/app.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.css, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.ts
VIH-10752
* display username in header
* make header sticky via css
* keep actions available, and not linked to connection service
=> VIH-10752 display username in header

AdminWebsite/AdminWebsite/ClientApp/.eslintrc.js, AdminWebsite/AdminWebsite/ClientApp/package-lock.json, AdminWebsite/AdminWebsite/ClientApp/package.json, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/booking.module.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/endpoints.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/models/video-access-point.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-form/video-endpoint-form.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-form/video-endpoint-form.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-form/video-endpoint-form.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-item/video-endpoint-item.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-item/video-endpoint-item.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-item/video-endpoint-item.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-item/video-endpoint-item.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-list/video-endpoint-list.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-list/video-endpoint-list.component.scss, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-list/video-endpoint-list.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/endpoints/video-endpoint-list/video-endpoint-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/participant/list/participant-list.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/common/model/defence-advocate.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/dashboard/dashboard.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/shared/header/header.component.css, AdminWebsite/AdminWebsite/ClientApp/src/styles.scss
[VIH-10745](https://tools.hmcts.net/jira/browse/VIH-10745)
Updated the Video Access Points into smaller components
Matches the look and feel of the JoH and Participants page
=> VIH-10745 Update Video Endpoints page look and feel

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/booking-details/booking-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/booking.service.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/video-hearings.service.ts
[VIH-10768](https://tools.hmcts.net/jira/browse/VIH-10768)
added restriction for more than 40 days multiday hearing
=> VIH-10768 - Block edit of this and future days in multi days hearings over 40 days in length

AdminWebsite/AdminWebsite.UnitTests/Middleware/VhApiLoggingDelegatingHandlerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/AppRoleServiceTests.cs, AdminWebsite/AdminWebsite/Extensions/ConfigureServicesExtensions.cs, AdminWebsite/AdminWebsite/Middleware/VhApiLoggingDelegatingHandler.cs, AdminWebsite/AdminWebsite/Security/Authentication/AadSchemeBase.cs, AdminWebsite/AdminWebsite/Services/AppRoleService.cs
VIH-10836 
handle concurrent calls to getting additional claims and handle no claims with a default value
=> VIH-10836 handle concurrent calls to get additional claims

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/interpreter-form/interpreter-form.component.ts
VIH-10828
set value instead of reset form to avoid marking form as pristine when pre-populating
=> VIH-10828 bug fix setting interpreter language to none should display required error

AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/common/constants.ts, AdminWebsite/AdminWebsite/Contracts/Requests/EndpointRequest.cs, AdminWebsite/AdminWebsite/Contracts/Requests/JudiciaryParticipantRequest.cs, AdminWebsite/AdminWebsite/Contracts/Requests/ParticipantRequest.cs, AdminWebsite/AdminWebsite/Mappers/BookingDetailsRequestMapper.cs, AdminWebsite/AdminWebsite/Models/EditEndpointRequest.cs, AdminWebsite/AdminWebsite/Models/EditParticipantRequest.cs, AdminWebsite/AdminWebsite/packages.lock.json, charts/vh-admin-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-8198
allow accented letters in display name field in admin web booking form
=> VIH-8198 - allow accented letters in display name field in admin web booking form

AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingRolesControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/ReferenceDataControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/ReferenceDataServiceTests.cs, AdminWebsite/AdminWebsite/Controllers/HearingRolesController.cs, AdminWebsite/AdminWebsite/Controllers/ReferenceDataController.cs, AdminWebsite/AdminWebsite/Extensions/CacheInitialisation.cs, AdminWebsite/AdminWebsite/Extensions/ConfigureServicesExtensions.cs, AdminWebsite/AdminWebsite/Services/ReferenceDataService.cs, AdminWebsite/AdminWebsite/Startup.cs
VIH-10842
cache static data on start up
=> VIH-10842 cache static data on start up

AdminWebsite/AdminWebsite.UnitTests/Controllers/ConfigSettingsControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/EditHearingTests.cs, AdminWebsite/AdminWebsite.UnitTests/Controllers/HearingsController/HearingsControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/clients/api-client.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/services/reference-data.service.ts, AdminWebsite/AdminWebsite/Configuration/VodafoneConfiguration.cs, AdminWebsite/AdminWebsite/Contracts/Responses/ClientSettingsResponse.cs, AdminWebsite/AdminWebsite/Controllers/ConfigSettingsController.cs, AdminWebsite/AdminWebsite/Startup.cs, charts/vh-admin-web/Chart.yaml, charts/vh-admin-web/values.dev.template.yaml, charts/vh-admin-web/values.yaml
https://tools.hmcts.net/jira/browse/VIH-10984
Updated to use vodafone phone numbers and removed JoinByDate as this has been redundant for years
=> VIH-10984 Use vodafone telephone number

AdminWebsite/AdminWebsite.IntegrationTests/appsettings.json, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/appsettings.json, AdminWebsite/docker-compose.override.yml, README.md, setup-secrets.sh
VIH-10993
Update implementation of reading key per file to reload on change
* [`setup-secrets.sh`](diffhunk://#diff-88e533a6137b5f19e2a62de2352166591ce7df23addbdaeb598055e889ad3c1aR1-R77): Added a new script to set up secrets by extracting values from a YAML file and storing them in a specified directory.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L17-R38): Added instructions for running the app as a container and using Docker Compose.
=> VIH-10993 reload on config change enabled

AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/Program.cs, AdminWebsite/AdminWebsite/packages.lock.json
VIH-10993
* reload on config change for secret by file
* Remove deprecated VH.Core.Configuration
=> VIH-10993 reload config on change

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/screening/screening-form.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/screening/screening-form.component.ts
VIH-11034
Remove the ability to choose measure type from the `ScreeningFormComponent`. It will be hard-coded to specific.
=> VIH-11034 remove the measure type radio group from screening measure

AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumb.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/breadcrumb/breadcrumbItem.model.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/judicial-office-holders/search-for-judicial-member/search-for-judicial-member.component.html
[VIH-11045](https://tools.hmcts.net/jira/browse/VIH-11045)
refactor tabindex
=> VIH-11045 Accessibility on Assign a presiding judge field

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
enable demo image and helm build & push
=> VIH-11181 enable demo image and helm build & push

AdminWebsite/AdminWebsite/ClientApp/src/app/bookings-list/hearing-details/hearing-details.component.html
https://tools.hmcts.net/jira/browse/VIH-11235
Fixes an issue with the video participant link containing a null hearing ref id
=> VIH-11235 Fix video participant link

.github/workflows/launch-darkly-find-code-refs-in-pr.yml, .github/workflows/launch-darkly-flag-sync.yml, .github/workflows/osv-scanner-pr.yml
VIH-11246
Update to the GitHub Actions:
* Switch the full LD code scan to run against master only and on a schedule
* Add the LD code scan on diff to run against PRs only
* Turn off fail on vuln for OSV scanner
=> VIH-11246 Update GH actions

AdminWebsite/AdminWebsite.IntegrationTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.IntegrationTests/packages.lock.json, AdminWebsite/AdminWebsite.UnitTests/Controllers/UserDataControllerTests.cs, AdminWebsite/AdminWebsite.UnitTests/Services/UserAccountServiceTests.cs, AdminWebsite/AdminWebsite.UnitTests/packages.lock.json, AdminWebsite/AdminWebsite/AdminWebsite.csproj, AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts, AdminWebsite/AdminWebsite/Controllers/UserDataController.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs, AdminWebsite/AdminWebsite/packages.lock.json, charts/vh-admin-web/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10558
=> VIH-10558 user api clean up

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-release.yml, sds-git-version-config.yml
=> VIH-11126 Add Gitversioning

charts/vh-admin-web/Chart.yaml, charts/vh-admin-web/values.yaml
https://tools.hmcts.net/jira/browse/VIH-11295
Use latest Java base chart version so Azure Workload Identity is used
=> VIH-11295 java chart

AdminWebsite/AdminWebsite/ClientApp/src/app/security/logout.component.html, AdminWebsite/AdminWebsite/ClientApp/src/app/security/logout.component.spec.ts, AdminWebsite/AdminWebsite/ClientApp/src/app/security/logout.component.ts
[VIH-11320](https://tools.hmcts.net/jira/browse/VIH-11320)
added return to login link
=> VIH-11320 - Incorrect UI result when logout on admin web

AdminWebsite/AdminWebsite/Controllers/AudioPlatformController.cs, AdminWebsite/AdminWebsite/Controllers/HearingsController.cs, AdminWebsite/AdminWebsite/Extensions/Logging/AudioLogger.cs, AdminWebsite/AdminWebsite/Extensions/Logging/HearingLogger.cs, AdminWebsite/AdminWebsite/Extensions/Logging/ReferenceDataLogger.cs, AdminWebsite/AdminWebsite/Extensions/Logging/UserAccountLogger.cs, AdminWebsite/AdminWebsite/Services/HearingsService.cs, AdminWebsite/AdminWebsite/Services/ReferenceDataService.cs, AdminWebsite/AdminWebsite/Services/UserAccountService.cs
[VIH-9658](https://tools.hmcts.net/jira/browse/VIH-9658)
added logger adapters
=> VIH-9658 - Migrate to structured logging and utilise LoggerMessage in .net apps

.github/workflows/close-pr.yml
VIH-11409 
Update close-pr action to use correct branch var
=> VIH-11409 Update close-pr action to use correct branch var

AdminWebsite/AdminWebsite/Mappers/HearingDetailsResponseMapper.cs
[VIH-11399](https://tools.hmcts.net/jira/browse/VIH-11399)
added mapping for hearing venue name
=> VIH-11399 BookingList Page missing column on multiday hearing edit
